### ISSUE TITLE
WP10: App stuck at Splash.xaml, if the app is open and the user launches the app again

### ISSUE THREAD

**Issue by jp-weber** [Windows-XAML/Template10#325] opened 2015-11-11 17:33 UTC
I have no idea where the bug is, normally the app should jump on the MainPage.

tested with minimal project and WP10 Build 10581/10586.
![splashscreen](https://cloud.githubusercontent.com/assets/10946850/11097662/d3cd3410-88a0-11e5-9342-5fab904391b5.png)

**Comment by bc3tech** [comment] 2015-11-11 19:09
feels like dupe of #157

**Comment by chosenonehacks** [comment] 2015-11-12 10:52
same is #310

**Comment by DominikErnst** [comment] 2015-11-12 18:00
Same, when the App is started a 2nd time on a Phone. It starts normal when you kill the App via Taskmanager.

**Comment by JerryNixon** [comment] 2015-11-13 06:05
With Mobile RTM about to be released, we can start to debug this properly. I am currently touring on a bunch of W10 events and will not be able to do anything here for about two weeks. Anyone wanting to make progress on this is welcome to help out. I will not close this issue out like the others.

**Comment by bc3tech** [comment] 2015-11-13 17:10
May have found a link here...

in `Bootstrapper.cs` we do this in `NavigationServiceFactory()`:

``` c#
var navigationService = new Services.NavigationService.NavigationService(frame);
navigationService.FrameFacade.BackButtonHandling = backButton;
WindowWrapper.Current().NavigationServices.Add(navigationService);
```

The problem with this is we are creating a brand new nav service every time we launch the app (even from suspend).
Where this really goes awry is when you ask for the App's `NavigationService` property value after this, where we do:

``` c#
public Services.NavigationService.INavigationService NavigationService => WindowWrapper.ActiveWrappers.First().NavigationServices.First();
```

which, as you can see, gets the **first** nav service ever created. This is **not** the **newest** (and therefore not the **active**) nav service.
So, when your app says "navigate to the first page" after suspend, it's doing so on a navigation service that's not the presently active one in the app.

I'm not sure why we're adding nav services if we only ever pull the first one. Is this something that is/should be used by multi-window apps, but is hampering single-window ones??

@JerryNixon

**Comment by bc3tech** [comment] 2015-11-13 17:36
I'm going to submit a PR that I believe will solve this problem.

I think root cause is we handle only `Window.Closing` which works great on desktop, but we **don't** do the same window/nav teardown for mobile during Suspending, which is what we should be doing (since there is no `Window.Closing` fired for Mobile).
So we're going to have some platform code in `OnSuspendingAsync` to essentially do what the `Window.Closing` handler is doing in `WindowWrapper`, but only for Mobile.

LMK what you think when you see it, @JerryNixon

**Closed as completed** 2015-11-15 06:49 UTC
Labels: bug, help wanted

**Comment by ozzy1873** [comment] 2015-12-24 18:16
This is still a bug in 1.0.9. And if you comment out the splash factory:

//SplashFactory = (e) => new Views.Splash(e);

Then you get an exception:

System.ArgumentException: Value does not fall within the expected range.
at
Windows.UI.Xaml.Controls.ContentControl.put_Content(Object value)
at
Template10.Common.Bootstrapper.NavigationServiceFactory(BackButton backButton, ExistingContent existingContent, Frame frame)
at
Template10.Common.Bootstrapper.NavigationServiceFactory(BackButton backButton, ExistingContent existingContent)

**Comment by SergioMorchon** [comment] 2016-03-06 23:21
If you add:

``` c#
        private bool NeedsNewNavigationService(IActivatedEventArgs args)
        {
            switch (args.PreviousExecutionState)
            {
                case ApplicationExecutionState.ClosedByUser:
                case ApplicationExecutionState.NotRunning:
                case ApplicationExecutionState.Terminated:
                    return true;
                case ApplicationExecutionState.Running:
                case ApplicationExecutionState.Suspended:
                    return false;
            }
            return true;
        }
```

and check for it on the `OnInitializeAsync` App method _before_ create a new Window content, it will run ok :)

In my case:

``` c#
        private bool NeedsNewNavigationService(IActivatedEventArgs args)
        {
            switch (args.PreviousExecutionState)
            {
                case ApplicationExecutionState.ClosedByUser:
                case ApplicationExecutionState.NotRunning:
                case ApplicationExecutionState.Terminated:
                    return true;
                case ApplicationExecutionState.Running:
                case ApplicationExecutionState.Suspended:
                    return false;
            }
            return true;
        }

        public override async Task OnInitializeAsync(IActivatedEventArgs args)
        {
            InstallVoiceCommands();
            if (NeedsNewNavigationService(args))
            {
                var nav = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);

                if (Window.Current.Content is ModalDialog)
                {
                    Window.Current.Content = new ModalDialog
                    {
                        DisableBackButtonWhenModal = true,
                        Content = new Views.Shell(nav),
                        ModalContent = new Views.Busy()
                    };
                }
                else
                {
                    Window.Current.Content = new Views.Shell(nav);
                }
            }
            await Task.CompletedTask;
        }
```

**Comment by MMalikKhan** [comment] 2016-11-21 20:35
@SergioMorchon @revan1199 @bc3tech Hi All, i remember this issue was fixed using the above workaround. However, in build 1.1.12 this came back and this time it is worst then ever, could you please take a look at this issue raised almost a month ago but so far no reply from @JerryNixon i tried to follow up multiple times but no result. This has become a show stopper for us, any workaround are appreciated. #1286
 I have added my findings so far in that issue, please let me know if you need any additional information.

**Comment by dg2k** [comment] 2016-11-21 22:25
@MMalikKhan 
The blank page issue as described in #1286.
Please check in your **CreateRootElement** override (in App.xaml.cs) the **NavigationServiceFactory** uses **ExistingContent.Include** and NOT **ExistingContent.Exclude** as follows:

`var service = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);`

**Comment by MMalikKhan** [comment] 2016-11-21 22:38
@dg2k aah finally at least someone looking after these threads .. i am not sure why no one is interested in replying to this issue #1286 . I changed this to include and it works .. thanks so much Mate!! .. i have issues at times the hamburger menu icons itself was disappearing .. i am not sure what is causing it to.. Is there something you know about it ? 

once again thank you .. @dg2k much appreciate your reply

**Comment by dg2k** [comment] 2016-11-21 23:04
Icons disappearing -- hard to speculate unless you narrow down the problem. Nothing to do with binding 'cos the icons are just glyphs just like text rather than bound icon images.

 Is the problem only on startup (in which case you have to check why Window.Current.Content isn't init'ed to non-null) or after startup (can't think of this at the moment)?

**Comment by MMalikKhan** [comment] 2016-11-22 04:07
Hi @dg2k, when you are on the details screen and want to go back to home page by selecting home button from the navigation menu. 

1. Click Hamburger, opens the navigation flyout on phone. 
2. Click on the Home page, which is list of around 500-800 items.. once clicked the home button text dis-appear making Home invisible, i believe it is same behaviour when you have a button with a command and it does long processing then the button first get disappear untill the button code is executed. I am not sure why the buttons behave like this in UWP. I believe, it is same for navigation menu when clicked and if it navigating to a page which has a large loading data then it just dis-appear .

Do you know, if i can do anything to keep the home button visible after click ..?
