### ISSUE TITLE
PageHeader NullReferenceException in NuGet 1.1.11

### ISSUE THREAD

**Issue by a-iafrate** [Windows-XAML/Template10#993] opened 2016-05-20 09:26 UTC
if i update template10 to latest version i have this exception

System.NullReferenceException: Object reference not set to an instance of an object.
   at Template10.Controls.PageHeader.UpdateSpacingToFitHamburgerMenu()
   at Template10.Controls.PageHeader.PageHeader_Loaded(Object sender, RoutedEventArgs e)

on this [line of code](https://github.com/Windows-XAML/Template10/blob/1a948f6de9020ae14c5fcd95457a708ccd5eea34/Template10%20%28Library%29/Controls/PageHeader.cs#L81)

the error is related to this piece of code but i cannot find why

[http://pastebin.com/gnJL8vJc](http://pastebin.com/gnJL8vJc)

thanks for your help!

**Comment by schuettecarsten** [comment] 2016-05-20 12:45
Take a look at line 183 in PageHeader.cs and set a breakpoint there. Is the "spacer" available in your XAML?

**Comment by mvermef** [comment] 2016-05-20 12:46
For starters you only have one appbarbutton in side the secondary tag, the rest are probably throwing the erroe

**Comment by JerryNixon** [comment] 2016-05-20 15:21
I can't dream up a single scenario where this error would occur except one. If the developer has changed the template of PageHeader and failed to put `spacer` in their template. I did not have a check for this before, but I will add one that we will ship with v12. In fact, I will add it now.

@a-iafrate is this your scenario? Have you possibly changed the template of PageHeader to do something specific in your application? If so, the only thing you would need to change is to add [this spacer](https://github.com/Windows-XAML/Template10/blob/1a948f6de9020ae14c5fcd95457a708ccd5eea34/Template10%20%28Library%29/Themes/PageHeader.xaml#L965) to your template so the null ref. doesn't occur.

**Comment by a-iafrate** [comment] 2016-05-20 15:38
Thanks to all for try to help me.
@JerryNixon i don't have changed the template, but i have a not common situation, i Page with PageHeader that include a usercontrol with another PageHeader.
The null for spacer is in the usercontrol PageHeader and not in the Page,
Thanks again!
thanks

**Comment by JerryNixon** [comment] 2016-05-20 16:13
You have two page headers on a single page?

**Comment by a-iafrate** [comment] 2016-05-20 16:18
yes and no :D
one in the page and one in the usercontrol in the page, and the page can have an array of this usercontrol, so i can have 1,2 or more pageheader in the page.
yes i know is not a common situation :D

**Comment by pekspro** [comment] 2016-05-20 18:23
I’m also got this problem when upgrading from preview 20160512 to 1.1.11.

I’m also have two page headers on some of my views. I have one header for “view mode” and another for “selection mode” (where you select items from a grid – just like the standard Photo app). These headers look quite different so it kind of make sense doing so. If I remove on header it’s no longer crash.

**Comment by drasticactions** [comment] 2016-05-21 03:35
This started happening in my apps as well when I updated, but I _think_ it's because OnApplyTemplate is not called if the control is not used in a base page. 

For example, [ThreadView.xaml](https://github.com/drasticactions/AwfulRedux/blob/master/AwfulRedux/Controls/ThreadView.xaml)

ThreadView.xaml a user control which has a PageHeader. I use this because it's a part of a Master/Detail control I also have. OnApplyTemplate is not being called from this control, so `spacer` is never set. As a result, I get an exception.

But on a page view, such as [ThreadListPage.xaml](https://github.com/drasticactions/AwfulRedux/blob/master/AwfulRedux/Views/ThreadListPage.xaml)

This works fine. No issues at all.

For reference, here is how it looks in the app (When it is working)

![Image](http://i.imgur.com/brfpmBX.png)

"Games" is the page level PageHeader, "UnReal World" is a part of the user control. This does not seem that strange to me because I want to keep a consistent header at the top of the page, and I like the master/detail flow with two separate titles.

**Comment by JerryNixon** [comment] 2016-05-25 01:45
We'll definitely resolve this. As soon as we understand it. 
I'm all ears, maybe @Windows-XAML/contributors see the issue?

**Comment by angusbreno** [comment] 2016-06-06 12:11
Same issue here, it happens on PageHeader sample too.

**Comment by angusbreno** [comment] 2016-06-06 12:37
What happens is this: 

OnApplyTemplate() is **only called when the control is Visible**. But our UpdateSpacingToFitHamburgerMenu() not.

In PageHeader sample u can notice this "behavior". 

Guys what is the best handle for this? @Windows-XAML/community

**Comment by tnesham** [comment] 2016-07-12 15:11
We converted our 8.1 project to use UWP with Template 10 and we started seeing the bug mentioned here. From what I can tell, all the fixes mentioned here exist in our ....nuget\packages\Template10\1.1.11\lib\uap10.0\Template10Library\Themes\PageHeader.xaml file.
We can use the PageHeader control in the usual way except we must use a modified copy of PageHeader.cs for the Styles in Custom.xaml (from Hamburger Template).  We do not have multiple PageHeaders or PageHeaders in UserControls.
I made an edit to correct what we are seeing, but we definitely are crashing with System.NullReferenceException: Object reference not set to an instance of an object.\r\n  
at Template10.Controls.PageHeader.UpdateSpacingToFitHamburgerMenu()

**Comment by angusbreno** [comment] 2016-07-12 17:03
@tnesham The nuget package it's not updated yet. This will be corrected in the next version...

**Comment by tnesham** [comment] 2016-07-12 17:05
@angusbreno Thanks for the reply. Any idea when the next version will be released?

**Comment by angusbreno** [comment] 2016-07-12 17:10
Only Jerry can tell u this...
https://github.com/Windows-XAML/Template10/milestone/8

**Comment by tnesham** [comment] 2016-07-12 17:15
Thanks. Btw, I discovered a page in our app that had two PageHeaders, and removing one fixed our issue.

**Comment by JerryNixon** [comment] 2016-07-12 23:43
https://github.com/Windows-XAML/Template10/issues/1113
The fix for this issue is not in the current preview.

**Comment by juanluelguerre** [comment] 2016-07-16 09:46
Hi,

First of all, thanks a lot for your effort. Good job about "Template 10", I'ts really great !!!

After Update (1.1.12-preview-160712), I can navigate without this bug, but not in all cases. No, when I've a button (+) in my Hamburger menu. One button like this:

`<ctrl10:HamburgerButtonInfo ClearHistory="True"
                            Tapped="NewProjectTapped">
    <StackPanel Orientation="Horizontal">
        <SymbolIcon Width="48"
                    Height="48"
                    Symbol="Add" />
        <TextBlock Margin="12,0,0,0"
                    VerticalAlignment="Center"
                    Text="New project" />
    </StackPanel>
</ctrl10:HamburgerButtonInfo>
`
And with this code behind, for the event:
public void NewProjectTapped(object sender, RoutedEventArgs e)
`{
    MyHamburgerMenu.NavigationService.Navigate(typeof(Views.ProjectEditionPage));
}`

When I click/tapp on it,  I have this error:
"Template10.Common.TemplatePartNotFoundException: Control part Spacer not found in Template.
   at Template10.Controls.PageHeader.GetTemplateChild[T](String name)
   at Template10.Controls.PageHeader.OnApplyTemplate()"

> I've just one PageHeader on my ProjectEditionPage. 

Thanks for your help.
Juanlu

**Comment by JerryNixon** [comment] 2016-09-22 00:08
This no longer seems like a reproducible bug. I have added a MultiplePageHeader sample in the Sample collection for you to review. It has more than one page header, more than one frame. Nested frames in User Controls. Everything I could think of to cause trouble. And I could not cause any. If you would take just a minute to review the sample and see if it covers your use case. I will close this bug on Friday if I don't hear back from you.

**Comment by juanluelguerre** [comment] 2016-09-22 22:00
The commmented line you can se below inside de VisualState is my problem:
`<VisualStateManager.VisualStateGroups>
    <VisualStateGroup x:Name="DeviceVisualStateGroup">
        <VisualState x:Name="DesktopVisualState">
            <VisualState.StateTriggers>
                <t:DeviceFamilyStateTrigger DeviceFamily="Desktop" />
            </VisualState.StateTriggers>
            <VisualState.Setters>
                <Setter Target="PageHeader.Visibility"
                        Value="Visible" />
                
            </VisualState.Setters>
        </VisualState>
        <VisualState x:Name="MobileVisualState">
`
So, "MainCommandBarStyle", cannot be assign directly using VisualState but if change code inside "Template10.Controls.PageHeader", it works perfectly.

Below my change:
`private T GetTemplateChild<T>(string name) where T : DependencyObject
{
    var child = GetTemplateChild(name) as T;
    if (child == null)
    {
        // throw new Common.TemplatePartNotFoundException($"Control part {name} not found in Template.");
    }
    return child;
}`

I can change my App XAML code, but this modification is much better, :-D.

**Comment by callummoffat** [comment] 2016-09-22 22:33
That exception was put there to prevent issues that could potentially cause
major problems. I don't think it's wise to remove it - it's probably there
for a good reason. 

It's causing problems in your particular use case, but I don't believe most
people will need to use that kind of implementation. More importantly, guidelines dictate that exceptions should only be thrown in exceptional circumstances and not just for any old thing. I can't imagine Jerry introducing exceptions without good reason - he's very good about following these guidelines.

**Comment by juanluelguerre** [comment] 2016-09-23 05:51
Yes, I know, and  I'll change my code to solve it, but it means I can't use this kind of "Setter" inside VisualState.
Probably I'm wrong but, If I use this style inside PageHeader it works but, why not inside the VisualState? Any reason for this?

Thanks a lot

**Comment by callummoffat** [comment] 2016-09-23 06:05
Why do you need a Setter there anyway? If you style it right, it shouldn't need those modifications.

**Comment by juanluelguerre** [comment] 2016-09-23 17:42
Because if I set Sytle inside VisualState, I can use my Page Header everytime (Desktop, Mobile, ...), with the same styles (Background color and text/title) and in adition, I show commandbar depending on the device. 
- In a Desktop.Text/tile and Command bar
- In a Mobile. Just text/tile to sow my text/title

**Comment by juanluelguerre** [comment] 2016-09-23 18:52
I've been trying some sentences but they don't work anyway.
1) This one doesn't hide command buttons.
`<Setter Target="PageHeader.PrimaryCommandsVisibility" Value="Collapsed" />`

2) I loose my PageHeader text/title
`<ctrl10:PageHeader x:Name="PageHeader"
                           Text="{Binding Title, Mode=TwoWay}"
                           Grid.ColumnSpan="2">
            <ctrl10:PageHeader.Content>
                <CommandBar x:Name="PageHeaderCommandBar" Style="{StaticResource MainCommandBarStyle}" />
            </ctrl10:PageHeader.Content>
        </ctrl10:PageHeader>`

**Comment by JerryNixon** [comment] 2016-09-23 22:02
Try this @juanluelguerre 

```
<pageheader>
    <appbarbutton x:Name="MyButton" />
</pageheader>
<visualstate>
    <setter target="MyButton.Visibility" value="collapsed" />
</visualstate>
```

**Closed as completed** 2016-09-23 22:03 UTC
Labels: bug, backlog

**Comment by juanluelguerre** [comment] 2016-09-24 09:11
Using it, could work but not in a best practices. I'm using two command bar. One visible in a desktop mode (PageHeader) and the other in mobile one. So If i try that you said, I have to create separated content and buttons for two command bar. That means two different command bar.
In any case, and afer all (reviweing your code) and I solved it just including "x:Name" in my style MainCommandBar !! Now spacer is not null and it works !
Hope this help. Could be a good practice to use PageHeader, ;)
Thanks a lot once again !

**Comment by juanluelguerre** [comment] 2016-09-24 12:28
Hi @JerryNixon ,

Using it, could work but not in a best practices. I'm using in my pages two command bar with the same content. One visible in a desktop mode (PageHeader) and the other in mobile one. So If I try that you said, I have to create separated Primary and Secondary buttons for two command bar. That means two different command bar in several pages. So "Copy & Paste" code in each pages !!!

**Workarround. Using ContentTemplateSelector:**
`<ctrl10:PageHeader x:Name="PageHeader"
                      Grid.ColumnSpan="2"
                      Text="{Binding Title, Mode=TwoWay}"
                      ContentTemplateSelector="{StaticResource DevicePageHeaderTemplateSelector}" />`

`<Grid Grid.Row="1"
          x:Name="ContentLayout">
  
  </Grid>`

`<Grid x:Name="BottomAppBar"
          Grid.ColumnSpan="2"
          Grid.Row="2"
          Visibility="Collapsed">
    <ContentPresenter ContentTemplate="{StaticResource MainCommandBarTemplate}" />
  </Grid>`

**Here my "DevicePageHeaderTemplateSelector":**
`public class DevicePageHeaderTemplateSelector : DataTemplateSelector
 {
 protected override DataTemplate SelectTemplateCore (object item, DependencyObject container)
 {
      var header = container as PageHeader;

```
    // if (header.Tag is string && header.Tag as string != "Mobile")
    if (!DeviceInformationService.IsMobile())
    {
        CommandBar cmb = null;
        var obj = CommandBarTemplate.LoadContent();
        if (obj is CommandBar)
        {
            cmb = (CommandBar)obj;

            // Asign Comands just one
            if (header.PrimaryCommands?.Count == 0)
                foreach (var b in cmb.PrimaryCommands)
                    header.PrimaryCommands.Add(b);

            // Asign Comands just one
            if (header.SecondaryCommands?.Count == 0)
                foreach (var b in cmb.SecondaryCommands)
                    header.SecondaryCommands.Add(b);
        }

        return this.CommandBarTemplate;
    }
    return this.EmptyCommandBarTemplate;
}

public DataTemplate EmptyCommandBarTemplate { get; set; }
public DataTemplate CommandBarTemplate { get; set; }
```

}`

I my opinion, you could add a "CommandBar" Property,  inside PageHeader or allow set style.

Hope this help
Thanks

**Comment by tnesham** [comment] 2016-09-24 15:38
I am using version 1.18 of Template10 and I created a new UserControl with a PageHeader to display inside a page with a PageHeader, and I get the error:
Message = "System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Template10.Controls.PageHeader.UpdateSpacingToFitHamburgerMenu()\r\n   at Template10.Controls.PageHeader.PageHeader_Loaded(Object sender, RoutedEventArgs e)"

Of course I don't need a PageHeader control nested like that but just letting you know.

**Comment by callummoffat** [comment] 2016-09-25 00:08
Why do you need two PageHeaders? One is probably enough; it's possible to modify the design of a single PageHeader via adaptive UI patterns to suit different screen sizes and orientations. In fact, it's pretty simple (especially using Blend).

**Comment by juanluelguerre** [comment] 2016-09-25 12:53
No, I'm using just one PageHeader but, one more Command Bar. I'm working in the same way as you can see in the sample "BottomAppBar": [https://github.com/Windows-XAML/Template10/tree/master/Samples/BottomAppBar.
](url)
