### ISSUE TITLE
Navigate() in OnNavigatedTo fails

### ISSUE THREAD

**Issue by crazycreak** [Windows-XAML/Template10#444] opened 2016-01-02 16:59 UTC
Hey,
i love your template, but i have the following problem: when i use "NavigationService.Navigate" in the "MainPageViewModel" class constructor the following error occurs:
- An exception of type 'System.NullReferenceException' occurred
##### example:

``` c#
public class MainPageViewModel : Mvvm.ViewModelBase
{
    public MainPageViewModel()
    {
        NavigationService.Navigate(typeof(Views.SettingsPage));
    }
}
```

when i use "NavigationService.Navigate" in the "MainPage" class on "Page_Loaded" it navigate twice to the View.
##### example:

``` c#
public sealed partial class MainPage : Page
{
    public MainPage()
    {
    }

    public MainPageViewModel ViewModel => this.DataContext as MainPageViewModel;

    private void Page_Loaded(object sender, Windows.UI.Xaml.RoutedEventArgs e)
    {
        ViewModel.GotoPrivacy();
    }
}
```

when i try to call "ViewModel.GotoPrivacy();" in the "MainPage" constructor a "System.NullReferenceException" occurred.
##### example:

``` c#
public sealed partial class MainPage : Page
{
    public MainPage()
    {
        ViewModel.GotoPrivacy();
    }

    public MainPageViewModel ViewModel => this.DataContext as MainPageViewModel;
}
```

**Comment by mvermef** [comment] 2016-01-03 15:57
Do you have your DataContext in your Page xaml set?  
   `<Page.DataContext>`
       `<vms:MainPageViewModel  />`
    `</Page.DataContext>`

**Comment by crazycreak** [comment] 2016-01-03 16:28
Yes, my examples are from the template 10 minimal project.

**Comment by AmitBhatnagar24** [comment] 2016-01-06 16:55
Not sure why you are trying to navigate somewhere in your ViewModel's constructor, however your NullReferenceException is likely happening because the INavigationServicehasn't is set after the ViewModel is constructed.

Re-think your approach.

**Comment by AmitBhatnagar24** [comment] 2016-01-06 17:09
...in other words, try this in your MainPageViewModel:

```
public override void OnNavigatedTo(object parameter, NavigationMode mode, IDictionary<string, object> state)
{
    // some conditional logic here to only perform this navigate when necessary 
    NavigationService.Navigate(typeof(Views.SettingsPage));
}
```

**Comment by crazycreak** [comment] 2016-01-07 09:48
the reason why i want to navigate to another page at this time is because i check if a profile is available (localstorage variable)
if not i want to navigate to the profile create page (with the mainpage in the navigation backstack)

**Comment by crazycreak** [comment] 2016-01-08 16:42
I have tried to call "NavigationService.Navigate" in "OnNavigatedTo" but it doesn't work.

**Comment by JerryNixon** [comment] 2016-01-09 01:35
Calling NavigationService from your view-model constructor is not possible because the NavService is a property and properties are set only after the constructor has executed. This is the nature of C#.

Calling NavigationService from your page constructor is not possible because the view-model is created by the page, by InitializeCompoenent, in the constructor. The NavService must wait until after the page is instantiated to rely on the view-model being present, so the NavigationService property can be set.

Calling NavigationService from your view-model or your Page OnNavigatedTo() override also does not work, and this is the bug. I am not sure why the NavService is ignoring this request. From a common sense point of view, this should work. I am re-titling your bug.

**Comment by artfuldev** [comment] 2016-01-10 03:30
Ideally we should be caculating the PageType to be navigated to before calling "Navigate()". Isn't that recommended?

**Comment by artfuldev** [comment] 2016-01-10 03:32
Here it can be done in OnStartAsync(). Check if profile is available, make it part of an application-wide service that manages profile etc. when user logs in / out. Read first from storage if available, check if he's logged in, etc, then pick the page to navigate to from the App.OnStartAsync() method where in the Minimal project there is Navigate(typeof(MainPage)).

Am I making sense here?

**Comment by artfuldev** [comment] 2016-01-10 03:37
Basically we are facing an issue like [this](http://stackoverflow.com/questions/15739996/frame-navigation-in-xaml-return-false), and I would hardly call it a bug. If this behavior is to be fixed in the NavigationService, sure we can take it up.

**Comment by artfuldev** [comment] 2016-01-10 04:26
> Calling NavigationService from your view-model or your Page OnNavigatedTo() override also does not work, and this is the bug. I am not sure why the NavService is ignoring this request. From a common sense point of view, this should work.

What would be the correct way for it to work?
Let's discuss a scenario:
1. `App.xaml.cs` calls `Navigate(typeof(MainPage));`
2. `MainPage` has a DataContext of type `ViewModelBase`, so its `OnNaviagatedTo` is called.
3. In `MainPageViewModel`'s `OnNavigatedTo`, we call `NavigationService.Navigate(typeof(AccountPage))`.
4. Currently it does not work, because the `OnNavigatedTo` method that is executing for the `MainPageViewModel` is still part of the navigation. There is no way the `Frame` can complete its initial navigation to the `MainPage` before the `MainPageViewModel.OnNavigatedTo` completes. So `Frame.Navigate` in `FrameFacade` will always return false at this situation.
   
   a. We say this is the expected behavior, and PageType must be decided before calling `Navigate()`. Exit.
   b. We try to allow calling Navigate from within `OnNavigatedTo` of a ViewModel. We need to make `FrameFacade.Navigate` call `Frame.Navigate` on `Frame.Dispatcher` which will complete the navigation. `Frame.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () => Frame.Navigate(page, parameter, infoOverride));` But now that we have used Dispatcher, we have lost the ability to return the result of the `Frame.Navigate()` method. If we try

```
var result = false;
Frame.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () => result = Frame.Navigate(page, parameter, infoOverride)).AsTask().Wait();
return result;
```

it will always return false, because of point number `4`.

Let's say we ignore the fact that we can't return the result and proceed. What will that lead to?

5.We implement `Frame.Dispatcher.RunAsync` in `FrameFacade` and get the user to the `AccountPage`. Here's the kicker. Now the Navigation Stack is ruptured. Back Button will be visible, but whenever Back is requested, navigation to `MainPage` will occur, _which will force navigation to `AccountPage`_, so we have a **"Back that never works"**, in a sense. So now we have two options.

  a. Say we can't do this, it's too much cognitive load for a developer, and not allowed in the framework for good reason.
  b. Say we will fix this. The only thing we need to do is to provide a separate method for navigating from within an OnNavigated method, which should handle the backstack properly.

Are we going with 5b?

**Comment by artfuldev** [comment] 2016-01-10 04:29
If we try to do anything with the `DispatcherWrapper` in the `ViewModelBase`,

```
Dispatcher.Dispatch(()=>NavigationService.Navigate(typeof(AccountPage)));
```

that will also fail because we check `Dispatcher.HasThreadAccess` and execute the `Navigate` directly, which will again take us to point no. `4`.

**Comment by artfuldev** [comment] 2016-01-10 04:50
It's probably over enthusiasm and rookie-ness, please forgive if I've missed anything or made mistakes :)

**Comment by JerryNixon** [comment] 2016-01-15 23:18
I follow you. Great points.

**Comment by JerryNixon** [comment] 2016-01-15 23:28
This has been resolved.

**Closed as completed by JerryNixon** 2016-01-15 23:28 UTC
Labels: bug

**Comment by JerryNixon** [comment] 2016-01-15 23:31
You will wnt to handle it like this in your OnNavTo()

```
if (NavigationService.Navigate(typeof(Views.SettingsPage)))
    NavigationService.Frame.BackStack.Remove(NavigationService.Frame.BackStack.Last());
```

**Comment by paulaenterpriseappsuk** [comment] 2016-06-19 01:14
Hi Jerry, 
I get 
An exception of type 'System.NullReferenceException' occurred
at the line 
`public void GotoSettings() =>
            NavigationService.Navigate(typeof(Views.SettingsPage), 0);`
