### ISSUE TITLE
Issues with 'Microsoft.Xaml.Interactivity in latest version

### ISSUE THREAD

**Issue by bdollerup** [Windows-XAML/Template10#914] opened 2016-05-04 13:06 UTC
Folks,

It's really hard to use this otherwise great template, when the designer, the template and the rest of Visual Studio is working against you.

I keel seeing this error: 
"Could not load file or assembly 'Microsoft.Xaml.Interactivity, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)"
And my views are full of blue wavy lines when I use the controls from the template. If I add the controls (hamburger and pageheader) manually to the Template 10 blank, the project compiles, but the controls do not show up. Is there and ETA resolving the issue or is there a temporary fix?

Thanks,
Bjarne

**Comment by mitchcapper** [comment] 2016-05-04 14:00
This is a dupe of #904 see that for further discussion.

**Comment by darenm** [comment] 2016-05-04 16:02
Closed as dupe.

**Closed as completed by darenm** 2016-05-04 16:02 UTC
Labels: duplicate

**Comment by callummoffat** [comment] 2016-05-04 20:40
And #904 is a duplicate of #860. It's the circle of life!
