### ISSUE TITLE
DISCUSSION: Consider deprecating HamburgerMenu for NavigationView once the Fall Creators Update drops

### ISSUE THREAD

**Issue by callummoffat** [Windows-XAML/Template10#1464] opened 2017-05-13 09:30 UTC
@Windows-XAML/template-10-developer-community:

As you know, the T10 HamburgerMenu control was created because, quite simply, the SplitView sucked. Once the Fall Creators Update (v1709?) launches, that will happily no longer be the case. 

In the latest SDK preview, Microsoft introduced the NavigationView - a first-party control which performs the same function as the HamburgerMenu. The HamburgerMenu control has been a blight on the library - while it does make things easier for devs, it has proven decidedly tricky to maintain and easy to break.

Therefore, I propose removing the HamburgerMenu control when T10 is updated for RS3. 

Discuss.

**Comment by bartlannoeye** [comment] 2017-05-13 14:29
While moving to NavigationView is the only logic way to go (over time), it also forces everyone to target Fall Creators Update. They'll have to exist side by side for e.g. a year to give developers the time to move, but mainly to give users the time to upgrade their system.

**Comment by mdtauk** [comment] 2017-05-13 15:13
@bartlannoeye  I agree, keep the code for maintenance, but have templates that target NavigationView

**Comment by Quico20** [comment] 2017-05-13 22:48
Well I have an Alienware 18 R3, and I cant Update to Windows 10 Creators, because there are no drivers yet published by Dell for my Alienware Model. So if the hamburguer menu is deprecated by template 10, it will be a pain for me to update my app now.

**Comment by IIARROWS** [comment] 2017-05-13 23:01
What?
You don't need new driver for the Creators Update...

Da: notifications@github.com
Inviato: 14 maggio 2017 00:49
A: Template10@noreply.github.com
Rispondi a: reply@reply.github.com
Cc: II_ARROWS@hotmail.it; team_mention@noreply.github.com
Oggetto: Re: [Windows-XAML/Template10] DISCUSSION: Consider deprecating HamburgerMenu for NavigationView once the Fall Creators Update drops (#1464)



Well I have an Alienware 18 R3, and I cant Update to Windows 10 Creators, because there are no drivers yet published by Dell for my Alienware Model. So if the hamburguer menu is deprecated by template 10, it will be a pain for me to update my app now.

**Comment by rpedretti** [comment] 2017-05-13 23:11
What about on mobile? Some devices might not be illegible for future updates. So removing the hamburger menu would require two code bases.

**Comment by Quico20** [comment] 2017-05-13 23:17
Well I updated to creators but any of my laptop hardware seems to work. Like wifi, bluetooth,  even the rj45 port didnt work. So I had to return to the previous version of windows 10. @IIARROWS

**Comment by mvermef** [comment] 2017-05-14 00:43
That's crazy, that update shouldn't have changed drivers that greatly. Quite surprising.

**Comment by Chris-Marassovich** [comment] 2017-05-14 00:48
Good morning everyone,

T10 is a template of great stuff to help accelerate development.
It should not replicate existing controls and I agree it is time to deprecate the Hamburger Control as there is a satisfactory one in Windows 10 (creators update).

BUT there are issues with the timing and rollout of that Creators Update.
For example as of two weeks ago that update was not supported on the Surface Pro 3.  I know cause I forced the update and destroyed my install.
This fact was confirmed by Microsoft Support who assisted in rolling back the update.  I understand it will be supported on the Surface Pro 3 in the next few days/weeks.

I suspect other hardware will be supported but over time.
The question is how over time will T10 transition away from the Hamburger control and what will it have in place to assist that transition?
Doco etc. on how to move your app over to the T10 version that no longer has the control and potentially how to stay with the old version of T10 as you cannot move your app for various reasons.

This is a great community and a great product.

Thanks.
Chris Marassovich

**Comment by callummoffat** [comment] 2017-05-14 00:51
It is supported on Surface Pro 3. I run it on my Surface Pro 3, as well as later builds from WIF. Probably software related, given that evidence.




Get Outlook for Android







On Sun, May 14, 2017 at 12:49 PM +1200, "Chris Marassovich" <notifications@github.com> wrote:










Good morning everyone,



T10 is a template of great stuff to help accelerate development.

It should not replicate existing controls and I agree it is time to deprecate the Hamburger Control as there is a satisfactory one in Windows 10 (creators update).



BUT there are issues with the timing and rollout of that Creators Update.

For example as of two weeks ago that update was not supported on the Surface Pro 3.  I know cause I forced the update and destroyed my install.

This fact was confirmed by Microsoft Support who assisted in rolling back the update.  I understand it will be supported on the Surface Pro 3 in the next few days/weeks.



I suspect other hardware will be supported but over time.

The question is how over time will T10 transition away from the Hamburger control and what will it have in place to assist that transition?

Doco etc. on how to move your app over to the T10 version that no longer has the control and potentially how to stay with the old version of T10 as you cannot move your app for various reasons.



This is a great community and a great product.



Thanks.

Chris Marassovich

**Comment by calloncampbell** [comment] 2017-05-14 00:57
Curious about the surface pro 3 not supporting the creators update. Im running it just fine and got it through windows update – well I forced it through windows update…but no issues were raised when it was checking the system prior to update.

As for the hamburger menu , I agree that if there is a suited replacement then I would just deprecate and let it sunset over time.

Callon

Sent from my Windows 10 phone

**Comment by callummoffat** [comment] 2017-05-14 01:00
Agreed on both counts.




Get Outlook for Android







On Sun, May 14, 2017 at 12:57 PM +1200, "Callon Campbell" <notifications@github.com> wrote:










Curious about the surface pro 3 not supporting the creators update. Im running it just fine and got it through windows update – well I forced it through windows update…but no issues were raised when it was checking the system prior to update.



As for the hamburger menu , I agree that if there is a suited replacement then I would just deprecate and let it sunset over time.



Callon



Sent from my Windows 10 phone

**Comment by callummoffat** [comment] 2017-05-14 02:29
Well, I think it has to happen in the long term. HamburgerMenu was created because the first-party controls couldn't meet the needs of many developers. I've been trying out NavigationView the last 24 hours and it definitely matches (and in many ways, exceeds) the goals and virtues of HamburgerMenu.

Personally, I think we should move sooner rather than later. This class is already supported on the Creators Update, and it also provides in-built support for Fluent Design. It's a worthwhile move, esp. given that HamburgerMenu is probably one of the most painful parts of T10 to maintain.

**Comment by mvermef** [comment] 2017-05-14 02:39
I am running 16193 which is 3 installs over CU working just on Surface Pro 3 i7 256.

**Comment by Chris-Marassovich** [comment] 2017-05-14 04:44
Callum,
I would very much appreciate hearing in detail your experience so far with the new NavigationView control.  The good, the bad and the ugly?

Cheers
Chris
________________________________

**Comment by callummoffat** [comment] 2017-05-14 05:28
Okay, Chris. (NOTE: This assessment of the NavigationView control is based off my experiences using it with the 16190 SDK – an early preview of the final SDK for the Fall Creators Update. My experiences here do not necessarily apply to the final product.)

THE GOOD:

1. Provides a standard hamburger menu implementation that works out of the box (unlike SplitView and like the T10 HamburgerMenu).
a. Provides the ability to configure a uniform header via a data template (can be turned off)
b. Supports nav menu separators, which T10 sadly does not
c. It also provides an inbuilt Settings button (which is probably the most universal navigation menu item on any platform).
2. Provides excellent customization functionality, and integrates with MVVM very nicely.
3. Provides in-built support for Fluent Design Language, and supports the Creators Update (RS2) in addition to RS3.
4. Apps can still use the previous SplitView implementation if desired (although given the ease of implementation for NavigationView in comparison with SplitView, I hardly see why people wouldn’t.)
THE BAD:
1. The NavigationView does not support data binding with regards to the list of menu items (i.e. no ItemsSource/SelectedItem object).
a. While this is preferable in many ways (binding with a list being used for this purpose is fiddly at best), it does reduce the ability for the navigation items to be altered on the fly.
THE UGLY:
1. In this early implementation, there are some nasty bugs.
a. NavigationView.Header can be set, but it will not be shown (in fact, the XAML/codebehind for it will not even be compiled)
There you have it, folks.


Sent from Mail for Windows 10

**Comment by Chris-Marassovich** [comment] 2017-05-14 05:46
Callum,

Really appreciate your effort and quick response.
I do not have the update yet so I cannot play with code .. but is there doco somewhere on this new control other than that at https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns/navigationview

Your point 3. Fluent Design .. I assume that is stuff like NavigationView.showheader.compactview.isactive for a contrived example.
The supports Creators Update RS2 and RS3 ... what is that/what does that mean?

From the doc link above it seems the action of navigation is done from code behind and the navigation stack is not handled/managed .. I assume this is where “T10 to the rescue”?

Additionally I assume from the URL above that we would port to this quite simply by updating our Shell.xaml and slipping in the NavigationView and some small XAML changes and we will have just ported from Hamburger to NavigationView?
Do you see it being that easy Callum?

Cheers
Chris ...

**Comment by callummoffat** [comment] 2017-05-14 06:03
Fluent Design is Microsoft’s new design language – it supports much of the currently implemented Fluent Design effects OOB (Reveal, blur, etc.).

While the NavigationView only appears within the 16190+ SDK (RS3/Fall Creators Update), it is still fully supported on 15063 (i.e RS2/Creators Update/v1703).

Yes, the navigation component is a bit contrived at this point – that’s where I can see T10 stepping in. If this element doesn’t improve, I’d probably suggest creating a new version of the HamburgerMenu which derives from the NavigationView but adds proper nav support.

And finally, yes, swapping HamMenu for NavView and making the requisite XAML modifications is essentially the extent of the port (more or less, anyway).

Sent from Mail for Windows 10

**Comment by callummoffat** [comment] 2017-05-14 06:17
UPDATE: The custom NavigationView-based control with proper nav support is a no-go. Just made an attempt – the class has been sealed. They appear to be taking the ‘my way or the highway’ approach on this one. Which is smart IMHO – they tried the ‘do what you want’ approach with SplitView and that was a fiasco.

Sent from Mail for Windows 10

**Comment by Chris-Marassovich** [comment] 2017-05-14 06:52
Callum,

Appreciate your time, effort and quick responses.
You are either up very late or extremely close to my TZ (Canberra, Australia).

Cheers
Chris ...

**Comment by callummoffat** [comment] 2017-05-14 06:55
The latter, thankfully. I live in New Zealand, so I am very close to your TZ indeed.

Sent from Mail for Windows 10

**Comment by JerryNixon** [comment] 2017-05-19 23:23
There is a future where HamburgerMenu is deprecated and NavigationView is preferred. The interim, though, in my MSDN article on NavigationView (not yet published) is the many steps to extend the control in order to get reasonable behavior - especially MVVM support and advanced navigation including what Template 10 developers take for granted - like the back button.

**Closed as completed** 2017-05-19 23:23 UTC
