### ISSUE TITLE
Is Template10.2 still worked on?

### ISSUE THREAD

**Issue by Weasy666** [Windows-XAML/Template10#1661] opened 2018-09-13 15:04 UTC
Just curious, but is the new version of Template10 still in development or is it dead?

**Comment by darenm** [comment] 2018-09-13 15:11
Jerry and I were chatting about that on Monday. We have plans to get the new bits out over the next few weeks – work and life have gotten in the way lately.

**Comment by Weasy666** [comment] 2018-09-13 15:44
Thx, for the lightning fast answer. Daily life has priority, of course. Just nice to hear that this great project is not dead.

**Comment by JerryNixon** [comment] 2018-09-14 15:01
I am amazed how a few people in the open source community are so impatient and feel so entitled to the free code being written in repositories. That said, @Weasy666, it a refreshing reality that most developers are like you, and understand the conflict of real life and online life and are both understanding and willing to help. Thanks for understanding. Let me give you my current news on Template 10 version 2. Every year, on July 1, Microsoft resets its internal calendar for a new fiscal year. This included the second of two major reorganizations of my division, the first of which kept me preoccupied last year and this one these past few months. Finding the right balance and cadence to manage my new position and this open source effort has really been difficult for me. Clearly, I know the most about the code base, and I really do love it and want to keep working it - better said, will keep working it - am just now seeing how I can weasel some time to contribute enough time and code to pick up the momentum again. In the past I have told you that my goals are to release an update of the version 1 nuget package. I also need to update the VSIX to support new version of VS. And, of course, to get version 2 into nuget with its own VSIX so developers can start using it. It's a more long term goal to merge this into the prism repo - but that's still on my radar. Today, I am working on the samples for version 2 to make sure most edge cases  work. Anyone cloning master today should have a pretty solid experience. Meanwhile, I continue to plug along. UWP adoption inside the enterprise is approaching a critical time when, if Template 10 1 or 2 aren't up and ready, those developers are stuck building their own crap over and over for no reason. My goal is to get things ready. If anyone reading this wants to help prepare the 13-preview nupkg and/or update the VSIX for visual studio version next, I welcome those pull requests. In the meantime, thanks for checking in.

**Comment by JerryNixon** [comment] 2018-09-14 15:05
I want to say one more thing that isn't really relevant to this conversation but I wanted to say it anyway. I get pulled onto all kinds of projects. Writing all kinds of software for all kinds of platforms. Every time I return to UWP it's like a dream. The experience is so rich and the visuals are so smooth. From time to time XAML developers and WinRT developers complain because they do not have the fastest rocket ship they can imagine. But, we forget that most developers are writing in pathetic languages with terrible editors. Even Visual Studio can only do so much for other platforms. UWP is really great.

**Comment by Weasy666** [comment] 2018-09-14 16:38
@JerryNixon just to clarify Things. In no way was my question meant to rush you or put pressure on you. I was just worried that this project might be dead, and that would have been a shame.
I agree with you that UWP is a nice way to develop apps for Windows 10, especially the available tools since VS2017. This also isn't really relevant for this conversation, but i want to use this opportunity and ask a Microsoft employee. We both agree that UWP is a great platform, so why doesn't Microsoft push it more by setting a good example for other developers? I mean...if you say that Xamarin is part of UWP, then why is Microsoft using Electron for the new Skype and for (i think it is) To-Do? This are just two examples. Don't get me wrong, this is nothing against you, i'm just hoping that you, as an insider, are having better...heh...insight 🤪 Again, i'm just curious if there is a meaningful reason, of that you are maybe Aware, or if it was just a missed opportunity by Microsoft.
It's ok if you can't answer because of some information Policy or if you don't want to, i just didn't want to miss my opportunity in asking this 😄

**Comment by JerryNixon** [comment] 2018-09-14 19:56
Sure. Okay. Here’s my take on the things of the past (Jerry's perspective and opinion):

Windows Phone came out and the phone carriers, like Verizon, had far too little vision; they lined up behind Android and Iphone, forgetting a three-part competitive marketplace is the healthiest. 

The Windows Phone team tried to measure success of the platform by the number of apps in the Store. They started unnatural motions with our developer community, often encouraging bad behavior.

The Windows Phone team used the influx of apps in the Store as a marketing message, but it backfired on them because their strange motions resulted in more apps, but mostly low-quality apps. 

These gaffs handed both Android and Iphone marketers easy ammunition to continue to persuade phone carriers, like Verizon, that Windows Phone had very little real value, and they did. 

Then Windows 8 was released after years of development that excluded our internal .NET team; their go-to-market developer message was JavaScript was the future of desktop software development.

Enterprises enjoying Windows 7 and WPF/WinForms saw the direction of Windows 8 as an invalidation of their years of investment in the Microsoft platform. They started to consider alternative futures.

Windows 8 leaned heavily on the Windows app store. They had assumed consumer companies would clamor to be on the platform and Windows Phone developers were happy and were on their way.

Stunned by the lackluster response for Windows 8, the Microsoft CEO at the time made a crazy claim in a high-profile interview that, “we will have 100,000 apps in the store by the end of the year”.

Unable to recant his claim, Microsoft scrambled countless, unnatural motions with our developer community, regularly encouraging bad behavior. There was only one goal: 100,000 apps by year’s end.

The Microsoft developer community was locally shepherded by Microsoft MVPs, volunteers who ran meetups, spoke at conferences, and generally promoted the Microsoft platform. 

Unsure why Microsoft seemed to desperate for apps, they jumped on board, happy to help, hoping to understand, and someone obliged by their status as MVP. We held thousands of app workshops. 

Like the enterprise, many MVPs felt betrayed by Microsoft’s behavior around Windows 8, especially in the sudden and discourteous dropping of the popular Silverlight platform.

Aside: the Silverlight platform was dropped, not because it had problems, but because the Windows team had seen the WinRT platform as the new universal and ignored our customer’s investment.

Most MVPs were consultants to enterprises who thought there was writing on the wall with desktop technologies, and rightfully started shifting their local community agendas to open technologies.

Moreover, many MVPs start to feel less important. Their specialties, especially for Windows, feel in question, and Microsoft evangelism is at an all-time high of activity around the globe.

Because of the general quality of WinRT apps in the store, the opinion of the platform’s quality was suspect. And, since the platform was new, early problems were met with suspicion, not patience. 

The entire Windows team responsible, even the CEO would soon find themselves removed from Microsoft. The arrogance of the Windows team was considered old school and the core problem.

Soon, external Windows developers felt little support from their local communities. Internal Windows developers felt like they were missing the open source boat buoyed by an underlying community shift. 

External developers responded by stopping most WinRT projects and scorning developers just like them who decided to hold out and see what was going to happen.

Internal developers also stopped using the platform and we start seeing Microsoft products written in all kinds of technologies, usually not Windows-native. 

New management at Microsoft sensing the shift embraced it, resisting the arrogance of Windows, and even taking one step away from Windows and acting more open source than product-based.

Azure was resurrected, emerging as a real potential player in a giant, new marketplace. Its success was tied to adoption, and Microsoft recent track record of gaining adoption was terrible. 

All eyes turned to Azure as the new normal, this caused a lot of eyes to turn from Windows. Many internal employees on the Windows team left for the Azure team to ride the rising tide. 

Platform engineering, hamstrung with reduced resources recognized the need to change WinRT to UWP and started a process leaving external WinRT developers feeling, once again, abandoned. 

Desperate to reach their goals and to find a future home for the platform, they found it in the operating system itself which adopted UWP as the UI technology of Windows internally. 

Working hard to meet the memory and performance requirements of the operating system, UWP began to evolve in a way that seemed to ignore the external developer in favor of first-party.

Feeling confirmed, more external developers started investigating other technologies. Seeing the drift, Windows marketing reaches out with new developer motions, this time targeting other technologies.

Nervous that if the external community is lost it cannot be recovered, the Windows store begins supporting Win32 applications, Electron applications, and PWA apps with open arms. 

The key architects of the WinRT vision are thinned while the architects of the UWP vision remain vigilant, expanding the platform to include many new features never seen in Windows. 

Seeing existing enterprise customers who are sitting watching this craziness, they realize they must reach out to them, the best hope for the platform. They expose WinRT to Win32 apps. 

The enterprise, still using Windows 7 and not migrating to Windows 10 in any hurry, watch and listen but don’t bite at the new supported technologies, including the Windows Store for Business.

Then an important milestone passes. Hardware refresh. Enterprises start preparing for an all-out Windows 10 desktop migration. Migrating line of business apps is priority.

The platform team, having made the operating system happy, turns to the most optimistic developer community, .NET developers in the enterprise. They start introducing enterprise features again. 

A couple other things happen, too. The .NET community grows dramatically and unexpectedly thanks to the popularity of Code and the cross-platform .NET driver. Many of these are ex-Microsoft developers.

Meanwhile, non-enterprise developers still don’t see marketing motions or incentives to write apps. As a result, the Windows store slows & starts reflecting a regular marketplace, not an artificial one. 

The WinRT fever is long past, developers look at the platform with suspicion, uninformed developers think it’s a messed-up platform, and enterprises are just starting to consider how to adopt it.

And that’s where we are now. 

Well, almost.

The largest contributor to quality apps in the store becomes Microsoft. This work is surprisingly duplicated in Android and Apple app stores, dominating the stores’ top listings. Reviving Microsoft as a software company and setting up dramatic success for Office 365. 

Then Windows gets scooped under the Azure org and is no longer at odds with Azure. It is an Azure endpoint, and accounting recognizes its more than a third of our massive annual revenue. 

Windows investments start to change internally. Agendas tied to the Windows team start to align with Azure and a cohesive strategy starts to be reflected between these massive organizations. 

But, evangelism ends. The one voice into the local community straight from Redmond is transitioned away and the once-ubiquitous voice to developers is silenced. What will Microsoft do?

The MVP program receives a brand-new license. Without evangelists Windows Insiders and MVPs are suddenly elevated as important partners for Microsoft to reach developers again. This is great.

Azure fills the internal gap with a new group called the Cloud Developer Advocates, an A-team of friendly and open source specialists getting the word out about Azure services and tooling. 

As the MVP program reignites, as the Developer Advocates build, as the internal strategies align, and as the platform matures and adds enterprise capabilities – the future is unsure, but bright, nonetheless. 

Office 365 gives us a good starting conversation. The quality of our first-party apps demonstrates the potential of the platform. And as enterprises start to migrate, a new future is starting up.

That’s the way I see it.

PS: nothing here that hasn't been all over the news. I just put it into a timeline for you.

**Comment by Weasy666** [comment] 2018-09-14 22:55
Wow...just wow. I haven't, in the slightest, expected such an extensive answer. Thank you for taking the time. You are right that a lot of that was over the news, but your perspective helped me a lot in "understanding" what happend, at least with my limited understanding. So thanks for that. It feels like i opened some old wounds with my question....sorry about that.

**Comment by JerryNixon** [comment] 2018-09-15 19:19
Naw. All good. Still a fan. Closing this thread though.

**Closed as completed by JerryNixon** 2018-09-15 19:19 UTC
Labels: information
