### ISSUE TITLE
Inject own ISerializationService implementation into NavigationService

### ISSUE THREAD

**Issue by schlzber** [Windows-XAML/Template10#726] opened 2016-03-03 05:56 UTC
The default JsonSerializationService used in NavigationService is not suitable for my application. How can I inject my own implementation?

**Comment by JerryNixon** [comment] 2016-03-03 17:41
You want the parameter serialization to be custom? Why?

**Comment by schlzber** [comment] 2016-03-03 19:33
I use Entity Framework models as state objects for Navigation. When they were routed through NavigationService I get new instances back in my views and not the original ones. This breaks a lot of Things then because Navigation properties etc. don't work on These instances. Also they are not tracked by the DbContext.
When I implement my own ISerializationService I can represent their state just by class Name and id and could look it up in the context and get the original instance back.

**Comment by JerryNixon** [comment] 2016-03-04 17:03
Okay, I understand. The error is that the original object is not passed to your view-model. Now, I have to admit, I thought this was how it worked. I'm busy with another project for a few days. Can you confirm this is happening like that? We'll fix that if so. Sound okay?

**Comment by schlzber** [comment] 2016-03-04 18:41
Yes that is exactly what I observe in my app! Thanks a lot for fixing this!

**Comment by artfuldev** [comment] 2016-03-06 10:45
@JerryNixon, isn't it that when serializing and deserializing we _never_ get the same objects, but only identical objects?

**Comment by schlzber** [comment] 2016-03-08 06:43
@kenshinthebattosai: that is true. Therefore I thought it would be easier to inject the ISerializationService and it would also not break the existing behaviour.

**Comment by artfuldev** [comment] 2016-03-08 08:49
@schlzber Usually in such cases, we pass on the id of the entity as the navigation parameter, and look up the entity via the id in the repository. Is that not possible? Actually the Navigation Parameter is supposed to not be heavy, I myself don't support the cause of serializing an object and sending it across as a Navigation Parameter. However I can appreciate the use cases it covers. For your situation I think what I proposed should be good. Can you try to apply this to your scenario?

**Comment by schlzber** [comment] 2016-03-08 17:00
Yes that is possible but I didn't want to care about IDs in my ViewModels. My own ISerializationService could make that transparent.
Nevertheless thanks for that hint, I haven't thought of it yet ;-)

**Comment by schuettecarsten** [comment] 2016-03-08 18:42
Maybe it helps for you to add a method like this to SerializationService:

```
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static void UpdateJsonSerializationService(ISerializationService json)
        {
            _json = json;
        }
```

Then you can call `SerializationService.UpdateJsonSerializationService(new CustomSerializationService());` when you app starts. Of course, there are better solutions for this, but it should work in your case. @JerryNixon, what do you think?

But please note that this might have strong side effects when your app resumes from suspension/termination because you have to make sure that you custom method is set before anything is deserialized. I am not sure if this is possible.

I agree with @kenshinthebattosai, you should try to pass information you need to identify your records in the database or wherever you need to load the data from. Then load the data in the target view/viewmodel. Do not pass the whole entity if possible.

**Comment by JerryNixon** [comment] 2016-04-21 22:55
I think this is a minuscule edge case. Is it really worth it?

**Comment by schlzber** [comment] 2016-04-21 22:58
I worked around it by using generic state objects that contain the ID and the type of the Entity and then I just look them up so I think I can live with that! ;-)

**Comment by artfuldev** [comment] 2016-04-22 05:16
@JerryNixon I think we can safely go ahead and close this.

**Closed as completed** 2016-05-07 01:13 UTC
Labels: bug, enhancement, help wanted, wontfix
