### ISSUE TITLE
Microsoft.Xaml.Interactivity, Version=1.0.3.0 is missing

### ISSUE THREAD

**Issue by GFlisch** [Windows-XAML/Template10#809] opened 2016-04-05 08:38 UTC
When I update the Template10 package to the version 1.1.8, I have a Microsoft.Xaml.Interactivity dependency issue.
The message is:
Severity    Code    Description Project File    Line    Suppression State
Error   CS0012  The type 'ActionCollection' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Xaml.Interactivity, Version=1.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   BelgiumGrid C:\Temp\BelgiumGrid\BelgiumGrid\obj\x86\Debug\XamlTypeInfo.g.cs 1819    Active

**Comment by vlastimilmaca** [comment] 2016-04-05 15:11
Duplicate of #801.

**Closed as completed** 2016-04-05 17:44 UTC
