### ISSUE TITLE
Image is flickering on extended splashscreen

### ISSUE THREAD

**Issue by JurajPupak** [Windows-XAML/Template10#913] opened 2016-05-04 08:42 UTC
When I use extended splashscreen, the image flickersbetween transitions. I found solution on MSDN to use timer and then call Window.Current.Activate(); Is it possible to make something similar using Template10?

**Comment by JerryNixon** [comment] 2016-05-05 18:17
The correct approach is not to use a timer but to let the Loaded event of the image in the Splash be the thing that accomplishes the activation. The problem is, we don't support that. In order to support that we would need to disable the activation in the bootstrapper. This could be okay but many developers do not use a splash screen and they would need to activate manually, which is unacceptable. Even developers who use a splash screen don't understand this minor nuance. The solution needs to be, I suppose, a variable approach to the splash screen. Perhaps we test for an interface, something like IActivatingSplashScreen without any implementation that I can test for, but that's just more tribal I don't ant to introduce into Template 10. Let me think on the best approach. Any ideas are welcome.

**Comment by JerryNixon** [comment] 2016-05-07 01:08
This has now been resolved with the introduction of 

````csharp
public virtual void ActivateWindow(ActivateWindowSources source)
````
into Bootstrapper. There's no sample for it yet.

**Comment by JerryNixon** [comment] 2016-05-12 16:56
What about this, @JurajPupak?

```
            Opacity = 0;
            splashImage.Loaded += (s, e) => Opacity = 1;
```

**Comment by JerryNixon** [comment] 2016-05-12 18:16
The latest version resolves this for you in a nice way.

**Closed as completed by JerryNixon** 2016-05-12 18:16 UTC
Labels: enhancement

**Comment by JurajPupak** [comment] 2016-05-12 18:31
Thank you Jerry. I'll try it :)
