### ISSUE TITLE
Building with Template10 crashes designer

### ISSUE THREAD

**Issue by kompiuter** [Windows-XAML/Template10#45] opened 2015-08-24 18:12 UTC
When building using the BootStrapper my XAML designer crashes.

-->

``` cs
An Unhandled Exception has occured
Click here to reload the designer
Details:
System.NullReferenceException
Object reference not set to an instance of an object.
   at Microsoft.MetadataReader.MetadataOnlyModule.GetNestedClassProps(Token tokenTypeDef)
   at Microsoft.MetadataReader.MetadataOnlyModule.GetEnclosingType(Token tokenTypeDef)
   at Microsoft.MetadataReader.MetadataOnlyTypeDef.get_DeclaringType()
   at Microsoft.MetadataReader.MetadataOnlyTypeDef.get_FullName()
   at Microsoft.VisualStudio.DesignTools.Platform.Metadata.ProjectContextType.get_FullName()
   at Microsoft.VisualStudio.DesignTools.XamlDesigner.DocumentModel.XamlProjectContext.RefreshUnbuiltTypeDescriptions()
   at Microsoft.VisualStudio.DesignTools.XamlDesigner.DocumentModel.XamlProjectContext.RebuildNamespaceMaps()
   at Microsoft.VisualStudio.DesignTools.XamlDesigner.Metadata.XamlProjectMetadata.OnAssemblyCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.VisualStudio.DesignTools.Designer.Project.ProjectAssemblyCollection.FireChangedEvent(NotifyCollectionChangedEventArgs eventArguments)
   at Microsoft.VisualStudio.DesignTools.Designer.Project.ProjectAssemblyCollection.AssemblyCollection_EnumerationChanged(Object sender, EnumerationChangedEventArgs`1 e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.VisualStudio.DesignTools.Utility.Collections.NotifyingCollectionBase`1.EventInvoker(EnumerationChangedEventArgs`1 eventArguments)
   at Microsoft.VisualStudio.DesignTools.Utility.Events.SuspendingEventManager`1.ForwardEvents()
   at Microsoft.VisualStudio.DesignTools.Utility.Events.Suspender.SuspendDisposer.Dispose(Boolean disposing)
   at Microsoft.VisualStudio.DesignTools.Utility.Events.Suspender.SuspendDisposer.Dispose()
   at Microsoft.VisualStudio.DesignTools.Designer.Assemblies.AssemblyCollection.AssemblyService_AssembliesUpdated(Object sender, EventArgs`1 e)
   at Microsoft.VisualStudio.DesignTools.Designer.Assemblies.AssemblyService.OnAssembliesUpdated(IEnumerable`1 assemblyInformation)
   at Microsoft.VisualStudio.DesignTools.Designer.Assemblies.AssemblyService.RefreshDesignerCaches()
   at Microsoft.VisualStudio.DesignTools.Utility.WindowsRuntimeService.SetIterationContext(String[] paths)
   at Microsoft.VisualStudio.DesignTools.Utility.WindowsRuntimeService.SynchronizeDesignerContext()
   at Microsoft.VisualStudio.DesignTools.Utility.WindowsRuntimeService.ProcessShadowCopyResults(IEnumerable`1 results)
   at Microsoft.VisualStudio.DesignTools.Designer.Assemblies.AssemblyService.FlushShadowCopyUpdateQueue()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.DesignerProcess.RunApplication()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.DesignerProcess.DesignProcessViewProvider.AppContainerDesignerProcessRun(String[] activationContextArgs)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.DesignerProcess.DesignProcessViewProvider.<>c__DisplayClass3_0.<applicationView_Activated>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by JerryNixon** [comment] 2015-08-24 20:38
Which XAML file are you attempting to open?

**Comment by JerryNixon** [comment] 2015-08-24 20:38
Can you confirm you have the Windows SDK installed?

**Comment by JerryNixon** [comment] 2015-08-24 20:38
Are you adding this to an existing project?

**Comment by kompiuter** [comment] 2015-08-24 22:43
This occurs when creating a new project and then either adding all template 10 assets to that project or referencing them directly from the Template10Library.
The designer then crashes on any XAML file, once the project is built.

**Comment by kompiuter** [comment] 2015-08-24 22:56
Here are a couple of images to hopefully make it clearer to you:
http://imgur.com/a/ccXip

**Comment by JerryNixon** [comment] 2015-08-26 04:33
I cannot reproduce this problem.

**Comment by JerryNixon** [comment] 2015-08-26 04:35
Could I ask you to rebase Template10Library?

**Comment by kompiuter** [comment] 2015-08-26 11:58
I'm new to github and I'm afraid I don't know what that is or how to do that.
I made a new project on another system today, referenced template 10 library and had the same problem. (Windows 10 pro, VS 15 community edition on both systems)

**Comment by JerryNixon** [comment] 2015-08-26 22:58
I have confirmed that this does not occur in the current build. This will be in Nuget tomorrow (maybe tonight) and I will build a demo after it is available.

**Closed as completed by JerryNixon** 2015-08-26 22:58 UTC
