### ISSUE TITLE
EFC Sqlite migration error

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#1109] opened 2016-07-10 14:05 UTC
Hi,
I've just started using template 10 and chose it to build my app. I've been using prism previously so the framework change has been really smooth.  Everything has been working fine but I got an error when I tried adding some
Entity framework core sqlite as my local dB.  I'm getting an 'object not set to an instance of an object' whenever I try to add a migration.
I haven't found any samples on integrating sqlite with template 10. Any help will be appreciated 
.

**Comment by dg2k** [comment] 2016-07-10 15:41
Although my suspicion is that this has less to do with T10, it's hard to guess what the issue is unless you provide more info. For example, show some code where your Sqlite code meets T10 code and the error is triggered. That may provide some clue.

**Comment by ghost** [comment] 2016-07-10 17:19
@mikemarango I made that same observation. I've been using EFC-sqlite in another project I created from a blank app and it's working perfectly, for some reason T10 is the only project it's failing.
I also implemented the tutorial from EFC documentation page. 

Do the previous versions of sqlite work? Maybe you can give me a heads up and save me the hustle of trying it out.

**Comment by mvermef** [comment] 2016-07-10 17:33
Keep in mind some key packages for EFC RTM are presently delisted due to some missing meta-data in the package for nuget, namely Microsoft.NETCore.UniversalWindowsPlatform, is missing some compressionclr stuff.  EFC requires version, 5.2.  There are workarounds, but you can't publish.  I haven't had any issues with migrations, I can publish some snippets of code later today.

**Comment by ghost** [comment] 2016-07-10 17:40
mvermef. Sure I'd like a look at the workaround. I don't think publishing will be an issue since I will be sideloading my app.

**Comment by mvermef** [comment] 2016-07-10 17:48
Yes, there is a performance issue with .net tool chain and includes. Have noticed 5.2 with hack is ok

**Comment by ghost** [comment] 2016-07-10 18:00
I've just tested out the sqlite 3 and it's playing nice with Prism and Template 10.

**Comment by mvermef** [comment] 2016-07-10 21:26
the only hack was "runtime.native.System.IO.Compression": "4.1.0" adding that as a dependency.  But to pull in 5.2 is to Update-Package or  Install-Package "Microsoft.NETCore.UniversalWindowsPlatform" -Version 5.2.0.  This force pulls the package.

as for migrations where you were attempting to do the migration, what errors are you seeing associated with it?.  I do them in the OnStartup and it has worked fine..

```
public override async Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
{
    using (var db = new ApplicationContext())
    {
        db.Database.Migrate();
    }

...
}
```

In my Context I have this

```
 protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite($"Filename=database.db");
    }
```

[UWP 5.2 Issues](https://github.com/dotnet/corefx/issues/9743)

oh I see now... you are bumping up on that pain in the ass issue.. now that I have read your issue... try doing it from the tools with CLI dotnet ef migrations add "NameOfMigration" -o <outputdir> it might and might not work.  This assumes RTM and Update 3 & Preview2 tools.  Make sure you are in the directory of your project.json file for your project.

**Comment by ghost** [comment] 2016-07-11 16:38
Hey mvermef...
I tried it out but unfortunately it's still refusing to work.  I guess out of frustration and to keep the solution simple I'll use the standard sqlite 3 with my app since it works so far. As for EFC SQLITE...I'll have to wait for a fix on the current incompatibility issue with template10

**Comment by mikemarango** [comment] 2016-07-11 18:01
@mbui83. I didn't try the previous version using a framework. Using blank App UWP(NetCore 5.2) EF.Core SQLite works fine. When I threw Prism into the mix the Xaml designer became none functional. I couldn't setup bindings coz I got an error that says GridView/ListView/Stackpanel cannot be a child of the Grid. The migrations and backend code work just fine. So yeah, a fix will do us some good.

**Comment by mvermef** [comment] 2016-07-11 18:35
It's probably a frame work and dependency issue with most still targeting 5.1 and not 5.2

**Comment by mvermef** [comment] 2016-07-14 06:27
>  I tried it out but unfortunately it's still refusing to work. I guess out of frustration and to keep the solution simple I'll use the standard sqlite 3 with my app since it works so far. As for EFC SQLITE...I'll have to wait for a fix on the current incompatibility issue with template10 

this wouldn't be a incompatibility with T10 its more of a compatibility issue with UWP atm. RC2-Final works all day long.  Preview2-Tools on the other hand (which released with RTM, are unfortunately buggy as hell, and still "Beta3", using the term loosely).

**Comment by ghost** [comment] 2016-07-14 06:56
Actually EFC-lite works perfectly with UWP. I tested it out the very first day the RTM came out. (i'm using the RTM for UWP and EFC-lite). It's only not working in T10 and prism 6.

**Closed as completed** 2016-07-29 06:25 UTC
