### ISSUE TITLE
DISCUSSION: should we continue to support Windows Phone?

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1494] opened 2017-06-05 23:08 UTC
Hey guys, don't read into this. This is less about "what I know about Windows Phone" and more about "what we want to support" when it comes to Template 10. Today, Template 10 is the second-most used library in the entire Store - second only to MVVM Light. So we need to start thinking about support breadth. Or, at least I do. We're going to start supporting Team, and likely certain parts of HoloLens, soon. I have not made a decision, I am just wondering - should we continue to support Windows Phone?

**Comment by dg2k** [comment] 2017-06-06 00:07
I am for continuing to support WP. By now we're all well used to adaptive design and with phablets and tablets still kicking around I see no massive savings in dropping the support for Windows Phone. Other than the VisualStateManager taken care of in XAML, the number of times you test for `AnalyticsInfo.VersionInfo.DeviceFamily.Equals("Windows.Mobile")` (in my experience)  is not that significant so don't think a massive efficiency gain really. But, then, others may disagree...

- PS:

By **Windows Phone**, we're talking about **Windows 10 Mobile**, the only WP running on the **UWP** platform.

**Comment by mvermef** [comment] 2017-06-06 00:43
I assume you are referring to Windows Phone as 8.x, not Windows Mobile 10... Then it's moot at this point unless MS gets some massive gain in market for "phone" share.  Don't get me wrong I am an early adopter love the platform, because it isn't apple or droid, if I jump platforms it will be to droid.  Otherwise based on definition of WP, what ever makes life easier for code life.

**Comment by callummoffat** [comment] 2017-06-06 00:45
I think he is referring to WP 8.x, given that T10 is a UWP framework and the only officially supported platform is UWP (ergo, W10M).

Thx, CJ

**Comment by mvermef** [comment] 2017-06-06 01:19
nvm was for something else... Was a badly written headline.

**Comment by callummoffat** [comment] 2017-06-06 01:24
It was always going to happen. Was just a matter of when.

Thx, CJ

**Comment by michaelhutchful** [comment] 2017-06-06 05:10
If it is Windows Phone 8 then yes, but i thought this was a Windows 10 only template? Anyways I develop for phone first, so this might hurt me.

Regards Michael

Sent from my Windows 10 phone

**Comment by mdtauk** [comment] 2017-06-06 18:04
Supporting Windows 10 mobile, should only be about accounting for narrow CoreWindow sizes, except for optional elements like StatusBar customisation surely?

Narrow/Small Windows will still have to be supported on Desktop, so needs to be catered for.

Is there anything directly in Template10 which specifically checks for the Phone APIs?

The Composable Shell is still in it's early stages, but it may also allow customisation of UI elements like a StatusBar/TaskBar which App developers will need to be able to address, right?

Unless you know differently of course.

Things like Acrylic work differently on Win10 mobile right now, so if you plan to implement these brushes, Reveal brushes, and the new native controls, I do not think these will arrive on mobile, and so will need to be addressed, maybe only as a legacy existing version of Template10

**Comment by JerryNixon** [comment] 2017-06-06 19:02
Wow, this became confusing fast somehow. Template 10 has never supported Windows Phone 8.x, so we can't stop supporting that now can we? I am talking about Windows Phone 10, that is to say, Windows 10 Mobile running on a cellular device. This isn't an issue of unique API, this is an issue of testing. If we support WP10 then it means I need to test on a WP10 device before I publish updates to any of the controls. Again, I am not saying this is unreasonable, I am just trying to judge if it matters. The usage of WP10 is desperately low compared to Desktop - and when you look at app development today it is for Desktop, not phone, not HoloLens, nothing as the significant numbers for Desktop.

**Comment by mdtauk** [comment] 2017-06-06 20:30
@JerryNixon  What about letting the community test updates on phones.  And add warnings until things are confirmed as working?  Hololens and Xbox should have lower numbers of potential users right?

And until we know what exactly is happening with a Windows 10 mobile SKU in the future, I don't think any steps should be taken to either block Template10 from working on mobile, and still add support to mobile app layouts for small windows on Desktop too.

**Comment by mvermef** [comment] 2017-06-06 20:49
Sorry for bringing the confusion to the table (function of Windows Phone and architecture fragmentation).  As far as @mdtauk has said I wouldn't block per se or limit function. 

 I do use it on a few applications at present for Table and Mobile needs (personal and commercial).  One my apps targets T10 for my colleagues to use on Surface tablets for union / non-union related stuff for pilots and flight attendants who have a related device.

As changes come into the system I evaluate those changes on the small screen sizes to make sure its staying true to form on a UWP supported platform.  As I actually love W10M.  Hate to see the low adoption but that is a function of dominance and horrid timing by MS once holding the Mobile sector. 

Due to usage being ultra low what did you have in mind of support, as far as testing for hardware buttons or screen size, that is pretty much all there is the need for imo.  Other than that most things UWP account for W10M already, obvious speed and battery differences aside.

**Comment by Chris-Marassovich** [comment] 2017-06-07 07:12
My $0.02 ... if UWP runs on a W10M device then surely T10 should support it.  T10 has supported it to date and that's why it, T10, is so high in the usage stats.

**Comment by JWH89** [comment] 2017-06-07 10:14
Completely agree with Chris-Marassovich

**Comment by callummoffat** [comment] 2017-06-07 20:53
The problem, of course, is resources. Which platforms should we invest our time in? Because they will all need lots of effort to maintain.

**Comment by HesamKashefi** [comment] 2017-06-08 19:16
I think there is a misunderstanding here! Microsoft created UWP only for helping Windows Mobile Store not adding something stupid to the desktop cause there is already the mighty WPF which is way better than UWP on desktop. I know there are currently way less users in mobile phones for windows (although MS says they'll have surprise in W10M devices) and Template 10 helps a lot but I'll stop using Template 10 if it does not support W10M. Actually I need to use newly added controls like NavigationView and T10 will come to this point too late so ...

**Comment by ryan-seifi** [comment] 2017-06-08 19:27
I don't agree to stop supporting W10M.
It's a part of Windows platform, so not a great idea to ignore that market.

**Comment by 0xNF** [comment] 2017-06-08 21:47
I see Microsoft's strategy as UWP applications being deployed to iOS and Android devices in the medium-term future. I don't have much to contribute regarding the specifics of Windows 10 Mobile testing, but if Microsoft does intend to deploy to those systems, then the experience of designing T10 apps for the form-factor of phones running W10M remains valuable. I don't know whether or not this has an effect on the decision to support W10M or not, but it seems like something worth thinking about anyway.

**Comment by richardcastle** [comment] 2017-06-18 19:27
Please don't stop supporting Windows Mobile 10. That's super important for us.

**Comment by myokeeh** [comment] 2017-06-23 20:11
Don't remove it until our foot's firmly on the next stepping stone.
Don't leave us hanging.
Don't pull the rug from under us.

So on and so forth...

**Comment by jp-weber** [comment] 2017-07-05 06:39
I agree with the continuation of the Windows Phone support/testing. Even if I understand that the proportion of WM10 based Windows Phones are still insignificant.

Because the question about Windows Phone 8.1 came up, actually I'm working at my hobby at a WP8.1 WinRT port of Template10. Is there actually still interest?

**Comment by firatesmer** [comment] 2017-07-05 11:31
> and when you look at app development today it is for Desktop, not phone

I don't agree. Also, If we stop support for Win10 it impacts store app. count.

**Comment by VagueGit** [comment] 2017-07-09 09:30
Sorry W10M developers; I can understand those who are already committed to W10M not wanting to see T10 drop support for W10M. We moved to UWP thinking we would have a desktop and phone app, however Microsoft didn't deliver users on phone so although we are continuing with UWP we no longer target phone.

I think developers starting a new UWP project will not be doing so because they think there is a phone market. I would rather see T10 move forward more quickly on platforms that have a viable user base rather than more slowly because it is trying to support platforms with a low user base. Perhaps T10 could refocus on W10M if the W10M market improved.

Again sorry W10M developers. I know what it means to be left high and dry. Life can be cruel.

**Comment by HesamKashefi** [comment] 2017-07-09 17:46
@VagueGit life is cruel for Microsoft developers cause it seems Microsoft is more interested in IOS and Android rather than Windows! even Microsoft Evangelists do the same!
Honestly I like developing apps for windows but this cruelty of life is pushing me toward Android and IOS (not just this Issue for Template10 , Microsoft is ignoring windows and moves toward other platforms and the cloud ...).

**Comment by JohaViss** [comment] 2017-07-11 07:48
Please don't drop support for Windows Phone 10.
I'm already very disappointed that you dropped support for VS2015.

We are a small company dedicated to write software that run on the entire Windows 10 platform. At this moment, Windows Phone 10 is the main focus point for us.

I think that UWP development should be integrated with Xamarin development to capture the entire mobile market. Now Xamarin and UWP are too different to use both.

Please let this not be another dead project. We had enough of those already.

**Comment by VagueGit** [comment] 2017-07-15 08:27
@HesamKashefi hit the nail on the head 

> 

it seems Microsoft is more interested in IOS and Android
--

Microsoft invested billions in trying to break into the phone market and failed. I don't think Microsoft can be blamed for recognising Android and IOS own that market and cutting their losses. @JerryNixon has limited resources for developing T10. I can't see the sense in those resources being spent on a market that Microsoft appears to have abandoned.

**Closed as completed** 2017-08-10 15:59 UTC
Labels: question, information
