### ISSUE TITLE
App hangs starting on a Windows 10 Mobile  Phone with Minimal Template10.

### ISSUE THREAD

**Issue by chosenonehacks** [Windows-XAML/Template10#310] opened 2015-11-07 20:30 UTC
Hello I need help...
I am using Template 10 Minimal in my project.

I have an issue while running my app. Whenever I suspend app from other views than MainPage view my views (even MainPage) can't load from suspended state...

Splash screen is stuck forever. However Shell view with hamburger menu is loaded and you can interact by choosing page.

Any clues what can be a reason for such behavior?

While I was investigating this problem I found that you can reproduce similar behavior when you comment line "NavigationService.Navigate(typeof(Views.MainPage));"  in app.xaml.cs 

public override async Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
        {
            await Task.Delay(50);
            //NavigationService.Navigate(typeof(Views.MainPage));
        }

Please help, I am stuck with almost complete app, but can't move forward. 
Thanks in advance.

**Comment by darenm** [comment] 2015-11-09 20:44
So your repro... all that does is block the initial navigation to the main page... so, of course, it won't navigate to the main page (if you are mentioning that so that we know what you are seeing in the restart after suspend & terminate , OK - we get it).

To the problem at hand - if you deploy the minimal template "as-is" to the phone, run the app, then navigate to detail by entering in something on main, then suspend and terminate - does the app start up showing the detail page? i.e. does suspend/resume work in the shipped minimal sample?

Does your app suspend / restart from termination fine when run on the desktop?

Have you tried debugging with first chance exceptions turned on to see if an exception is occurring and being masked somewhere?

I would also say it doesn't sound like the app is hanging if it is still responsive to the hamburger...

**Comment by chosenonehacks** [comment] 2015-11-09 21:20
Thank you Daren for you time spending on this issue.

Let me answer your questions:
ad1. "if you deploy the minimal template "as-is" to the phone ... does suspend/resume work in the shipped minimal sample?" 
No. Minimal template without any changes in code behave same way as my app. Also same on emulator.
Please take a look at this animated gif.: http://programuje.net/?attachment_id=624 

But to be more funny it never happens when you in debug mode, but only when you start app normal way (same on emulator/phone)

ad.2 "when run on the desktop?" Yes on desktop everything is fine in windowed mode, I can't try tablet mode in my Win 10.

ad.3 Nope I didn't will try right after I post this and give more info. But as I wrote before it never happens in debug mode.

To give more info I have latest available versions of emulators and UWP Tools with hot fix 1.1.1. But this was also happening in previous versions.

**Comment by darenm** [comment] 2015-11-09 21:27
So I looked at the GIF - can you tell me the context that you are starting the app in? I.e. have you run the app using visual studio, then selected suspend and terminate from the debug location menu, then relaunched the app? That is the only way to reliably suspend/terminate the app and set it up for state resume on reload. Due to the changes in app lifecycle, taking an app to the background doesn't guarantee that it has been suspended, and certainly doesn't mean it has been terminated. I'm setting up a machine so I can test also.

**Comment by chosenonehacks** [comment] 2015-11-09 21:45
I usually start up from VS (F5), then I hit stop, or sometimes suspend shutdown it doesn't matter anyway. Then after I start app from phone/emulator app list (as on gif) and then you saw, hamburger menu and everlasting splash view. You can interact with menu, but view like MainPage or something other will never load.

**Comment by darenm** [comment] 2015-11-09 21:57
OK - perhaps I have been focusing too much on your statement: 

"I have an issue while running my app. Whenever I suspend app from other views than MainPage view my views (even MainPage) can't load from suspended state..."

Is this just an issue that the app doesn't start on Mobile and is nothing to do with starting after suspension? The reason I am drawing a distinction is that the only time Template 10 attempts to recover state is if the app Previous Running State was Terminated - it does not recover state if the app was Closed By User. 

I'm setting up a machine so I can test on the emulator.

**Comment by chosenonehacks** [comment] 2015-11-09 22:22
I can't really say what state app is (since I am not deubging - it's not happening in debug mode), but for sure it is not loading view whenever you hit on app icon. I think it's from suspended state. Not start over.

**Comment by JerryNixon** [comment] 2015-11-10 04:22
Unless you debug this with a device, I will not chase the fix until RTM.

**Comment by chosenonehacks** [comment] 2015-11-10 09:03
Well that's not a good news for me with project almost finished. Does anyone have a workaround?
Anyway thanks Daren and Jerry to take this seriously for now.

**Comment by JerryNixon** [comment] 2015-11-11 03:16
You don't have a phone with W10? 
If not, email me your mailing address (jnixon@microsoft)

**Closed as completed by JerryNixon** 2015-11-11 03:16 UTC
Labels: platform bug

**Comment by darenm** [comment] 2015-11-11 15:46
FYI - I couldn't replicate.

**Comment by chosenonehacks** [comment] 2015-11-11 16:39
I will reinstall my development environment. Thanks again Daren.

**Comment by chosenonehacks** [comment] 2015-11-12 11:06
Reinstall didn't help... I see there a few cases very similar to mine. At least I am happy this is not only my issue.

**Comment by keneniah** [comment] 2015-12-03 19:18
Could we re-open this, please. I do have exactly the same issue. The app hangs when resuming from suspended state on my mobile phone running the latest windows 10 insider build.

**Comment by gardebring** [comment] 2015-12-05 21:49
Hi. I am having the same issue as well. Running on my Lumia 950 XL. The issue only occurs when running the application from the phone after having deployed it there. It never occurs when debugging, even when using the Lifecycle events options in Visual Studio. Just like with the other commenters I am able to navigate using the hamburger menu.

**Comment by gardebring** [comment] 2015-12-05 22:03
Bear with me since I am new to universal apps programming. I do not know if this is of any help, but since this seem to be related to the app getting stuck on the splash screen I tried to comment out the following line in App.xaml.cs:
SplashFactory = (e) => new Views.Splash(e);
When I do this, on resuming the app, it first exits and goes back to the start screen.
The second time I resume the app, it loads properly. The third time it exists, the fourth it loads again and so on.

**Comment by chosenonehacks** [comment] 2015-12-05 22:22
Guys for now this can be fixed by referencing Template10 libary project into your solution, and changing following files like in this link: https://github.com/bc3tech/Template10/commit/379b00b3d8c6ee7aef7f634041ef30cf6885b3cd 
However this fix will be released in 1.0.9 (https://github.com/Windows-XAML/Template10/milestones/NuGet%20Library%20v1.0.9) which means after that release you can download this as Nuget

**Comment by gardebring** [comment] 2015-12-06 00:23
Awesome @xorch !
I actually managed to get it working without referencing the library project into my solution, I simply added this to App.xaml.cs:

(probably a good idea to remove this once the new version is released, but as a temp fix it seems to do the trick for my app)

public static void ClearNavigationServices(Window window)
{
   var wrapperToRemove = WindowWrapper.ActiveWrappers.FirstOrDefault(wrapper => object.ReferenceEquals(wrapper.Window, window));
   if (wrapperToRemove != null)
   {
      wrapperToRemove.NavigationServices.Clear();
   }
}

public override Task OnSuspendingAsync(object s, SuspendingEventArgs e)  
{
   if (Windows.System.Profile.AnalyticsInfo.VersionInfo.DeviceFamily.Equals("Windows.Mobile")) { 
      ClearNavigationServices(Window.Current); 
   }
   return base.OnSuspendingAsync(s, e);
}

**Comment by chosenonehacks** [comment] 2015-12-06 08:57
You was smarter than me putting this into app.xaml.cs. Good luck :)  :+1:

**Comment by keneniah** [comment] 2015-12-06 10:27
I downloaded latest version here from GitHub and I can confirm that this issue is fixed in 1.0.9.

**Comment by gardebring** [comment] 2015-12-06 19:52
Not at all @xorch, the only work I did was finding out how I could take the changes from your commit and add it to my codebase to avoid having to reference the project. You found the actual issue :)
