### ISSUE TITLE
Hamburger Button in Narrow State 

### ISSUE THREAD

**Issue by TheSETJ** [Windows-XAML/Template10#1504] opened 2017-06-14 11:14 UTC
Hey

Hamburger Button's content seems to go invisible in Narrow Visual State when I open "more" menu. Here's a shot of what happens:

![capture](https://user-images.githubusercontent.com/10893088/27129601-51fb5ce0-5118-11e7-8551-a5b61016fe4d.PNG)

It's happening in Hamburger template completely untouched.

**Comment by TheSETJ** [comment] 2017-06-17 08:14
@darenm @JerryNixon

**Comment by swisszeni** [comment] 2017-06-20 17:27
Duplicate of #1349

**Comment by JerryNixon** [comment] 2017-06-28 03:59
@swisszeni suggestions? @TheSETJ what version of T10 are you using?

**Comment by TheSETJ** [comment] 2017-06-28 05:49
@JerryNixon v1.19.

**Comment by JerryNixon** [comment] 2017-07-28 16:39
What does that mean?

**Comment by TheSETJ** [comment] 2017-07-28 16:47
@JerryNixon version of T10 that I use.

**Comment by JerryNixon** [comment] 2017-08-14 04:22
Hmm. Okay. Well, do you see the issue when you update to 1.1.13-preview?

**Closed as completed** 2017-08-17 06:29 UTC
Labels: bug
