### ISSUE TITLE
Microsoft.Xaml.Interactivity - strongly-named assembly

### ISSUE THREAD

**Issue by mvermef** [Windows-XAML/Template10#860] opened 2016-04-22 02:01 UTC
Could not load file or assembly 'Microsoft.Xaml.Interactivity, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Seeing this on building projects off the code in git..

**Comment by callummoffat** [comment] 2016-04-22 02:22
So, you're only seeing this when building from the Git code?

Have you tried getting the latest code? I believe there was a strong-naming fix at some point recently.

**Comment by mvermef** [comment] 2016-04-22 03:58
its the absolute latested code, and it was happening yesterday source as well.  First time since the initial

**Comment by callummoffat** [comment] 2016-04-22 04:00
I think I know what the problem might be. I'm no expert, but is it possible that a strong-named assembly isn't being created when you compile the code from Github? It would explain the error (which I'm not receiving using 1.1.10 Nuget).

**Comment by mvermef** [comment] 2016-04-22 04:03
you are saying with respect to the Template10 strong name?
tried that as well and to no avail.

**Comment by mvermef** [comment] 2016-04-22 04:04
I hard reset my source and it has it selected with the key in the root of the library

**Comment by callummoffat** [comment] 2016-04-22 04:04
Not quite following. Are you saying that you are having this issue with the new Nuget package as well?

**Comment by mvermef** [comment] 2016-04-22 04:04
yes

**Comment by callummoffat** [comment] 2016-04-22 04:05
I think it might be to do with your app, and not Template10 itself. Like I say, I'm having no issues with it.

**Comment by callummoffat** [comment] 2016-04-22 04:07
Take a look in the project.json for your app. Have you updated the Behaviors SDK reference to 1.1.*? Because T10 1.1.10 now supports this as the baseline, and if you're basing your app of an older template, it won't have this configured correctly.

**Comment by mvermef** [comment] 2016-04-22 04:43
yes

**Comment by callummoffat** [comment] 2016-04-22 05:17
So you have updated the reference, and that's not the cause of the problem?

Well, I'm stumped. @JerryNixon, do you have any ideas?

**Comment by mvermef** [comment] 2016-04-22 05:41
went back to project to 1.1.10 and it updated latested without issue and no warnings about strong name, but compiled source not so lucky

**Comment by callummoffat** [comment] 2016-04-22 05:43
Still having trouble following, so correct me if I'm wrong, but when you use the 1.1.10 Nuget package, you have no problems, but using the Github sources, you get a strong name error?

**Comment by mvermef** [comment] 2016-04-22 08:09
~~ok, so the nuget compiles without warnings or errors~~
Neither build without that warning...
Source on git doesn't

**Comment by mvermef** [comment] 2016-04-22 08:35
1>C:\Program Files (x86)\MSBuild\Microsoft.NetNative\x86\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'sysctl!libc' in assembly 'Microsoft.Extensions.PlatformAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
1>C:\Program Files (x86)\MSBuild\Microsoft.NetNative\x86\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'uname!libc' in assembly 'Microsoft.Extensions.PlatformAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
1>C:\Program Files (x86)\MSBuild\Microsoft.NetNative\x86\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'RtlGetVersion!ntdll' in assembly 'Microsoft.Extensions.PlatformAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
1>  Generating serialization code

native tool chain warnings...

**Comment by darshanrampatel** [comment] 2016-04-22 09:42
I'm seeing this as well with the Nuget version - I've updated my project.json to `"Microsoft.Xaml.Behaviors.Uwp.Managed": "1.1.*",`

I get an exception when it first runs:
`Exception  {"Layout cycle detected.  Layout could not complete.\r\nLayout cycle detected.  Layout could not complete."}    System.Exception {Windows.UI.Xaml.LayoutCycleException}
`

**Comment by darenm** [comment] 2016-04-22 15:13
@darshanrampatel I suspect that is caused by an instance of `EllipsisBehavior` in your initial view - remove that behavior from your `PageHeader` control if you have it and try again.

**Comment by darenm** [comment] 2016-04-22 16:47
So I also see an issue with the error related to strong-named assembly for the Behaviors. It manifests as "blue wigglies" in the designer - mousing over gives the error:
![image](https://cloud.githubusercontent.com/assets/1674843/14748575/9e6d4e48-0877-11e6-9dd6-bc20b099ebe3.png)

**Comment by darshanrampatel** [comment] 2016-04-22 16:50
@darenm Yes, that was exactly it! Thanks.

**Comment by Ahaituka** [comment] 2016-04-22 16:52
I am also having the same problem with the nuget version of template 1.1.10. .But when i updated all my packages Earlier it was working fine but now its giving me blue underline over any  control  and when hovered the intellisense displays:
Could not load file or assembly 'Microsoft.Xaml.Interactivity, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
![2016-04-22 1](https://cloud.githubusercontent.com/assets/9658451/14748612/3e64715a-08d8-11e6-9068-1f04a563c9f3.png)

But weird thing is that my app is deployed and its running!

**Comment by mvermef** [comment] 2016-04-22 16:54
YES!!!, now I am also seeing namespaces for the Template10 being blue wiggled... Saying it doesn't exist, I cleaned and recompiled (release) the 1.1.10 source code.  Controls, Behaviors, Common, etc.

**Comment by darenm** [comment] 2016-04-22 17:17
Ultimately I suspect this is an issue caused by the Behaviors team electing to StrongName - there is a thread here on their repo: [Behavior Strong Naming Thread](https://github.com/Microsoft/XamlBehaviors/pull/29#issuecomment-162572491)

**Comment by JerryNixon** [comment] 2016-04-22 20:16
Good work. I am closing this, though I have money on how many hours until an identical one is opened :)

**Closed as completed by JerryNixon** 2016-04-22 20:16 UTC
Labels: question

**Comment by dubstylee** [comment] 2016-04-23 21:04
Why is this closed? It isn't fixed to my knowledge? I am having the same issue and do not have EllipsesBehavior, am referencing the correct 1.1.0 Behaviors, and have cleaned/rebuilt/refresh/restarted/re-added reference to Behaviors, and still having the same issue. The application works fine, but basically makes the Designer useless for any pages with a PageHeader.

**Comment by callummoffat** [comment] 2016-04-23 23:17
It's closed because we have determined this us not a Template 10 issue. Not
much we can do.

On Sunday, April 24, 2016, dubstylee <notifications@github.com> wrote:
> Why is this closed? It isn't fixed to my knowledge? I am having the same
issue and do not have EllipsesBehavior, am referencing the correct 1.1.0
Behaviors, and have cleaned/rebuilt/refresh/restarted/re-added reference to
Behaviors, and still having the same issue. The application works fine, but
basically makes the Designer useless for any pages with a PageHeader.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub<
https://ci6.googleusercontent.com/proxy/039Axle8BYoQyPvAjxViy92zQTNo9ZwriNp5_fz9r-WYAG3eSc1JwB3IQgU0PjtiOFJ9A2hzV7ph2opA-gvlHuctm0ZfoLgQcH_DLPQdoIvHC4_nViLvutRDRGUXMsLOodEJbp5dYkqDYW8PDN4Jnx2U9PZdsQ=s0-d-e1-ft#https://github.com/notifications/beacon/AM3pI0_hjWXP3sDEicUsx287oa-52eCUks5p6olXgaJpZM4INPIi.gif
>

-- 

*Callum Moffat*
App Developer
Windows 10 Enthusiast
__________________________________
Keep track of the costs of your vehicles with Petrolhead!
https://www.microsoft.com/en-us/store/apps/petrolhead/9nblggh1rjqt?cid=phmailsig

**Comment by callummoffat** [comment] 2016-04-24 03:07
This is closed because it isn't actually a Template 10 issue. It's to do with the Behaviors package, and a decision they made recently. They enabled strong-naming for behaviors for some reason, and it's causing issues. There's not much we can do about it, except hope that the Behaviors team resolves this somehow.

**Comment by IIARROWS** [comment] 2016-04-24 18:38
I disagree: Template 10 1.1.10 requires Behaviors 1.1.0, so I cannot update Template 10 without this really unpleasant collateral effect.

I still have to use 1.1.8 and Behaviors 1.0.3, if I want an header on my views.

**Comment by dubstylee** [comment] 2016-04-24 19:02
The header still works fine in the application at runtime, you just cannot get a preview in the designer is all.

**Comment by IIARROWS** [comment] 2016-04-24 19:08
Yes, I understand that, but is very annoying to read a XAML view when everything has that wiggly underline and it's hard to make changes.

It's not a blocking issue, but I still consider it an issue that is not unrelated to Template 10 until it's used and forced by Template 10.

**Comment by mvermef** [comment] 2016-04-24 20:19
One other thing to look at is that XamlBehaviors is also built on the lower dependency of 5.0 for `Microsoft.NETCore.UniversalWindowsPlatform`, not that it make much difference.  The other question to ask was there a pressing need or I missed the conversation to actually pushing forth to 5.1 and 1.1.0 respective? Everything seem to function correctly as we would have expected from the lower versions.

**Comment by JerryNixon** [comment] 2016-04-27 15:54
This behavior SDK thing is making me so frustrated.

**Comment by mvermef** [comment] 2016-04-27 16:12
What is even more infuriating is that it is not occurring any longer at least on my 2 projects, it's very strange.

**Comment by aline-almeida** [comment] 2016-04-27 16:45
I've started a new project with Nuget & hamburguer template. project.json looks right as described in 
#856 , cleaned & rebuilt. Still seeing this error and designer is blank...

**Comment by callummoffat** [comment] 2016-04-28 03:34
I've started getting this too. Curse you, Behaviors Nuget 1.1.0!

**Comment by alexdresko** [comment] 2016-04-28 14:07
Just FYI, if I click this button, the designer appears again, albeit without design time data... 

![image](https://cloud.githubusercontent.com/assets/333022/14888485/98965eb4-0d28-11e6-9d19-44ee3683e492.png)

I assume that button's purpose is to disable design time data, although the tool tip isn't extremely helpful in that regard. It was a totally random fluke that I stumbled across that button and it's affect on the designer related to this problem. 

Hope that helps someone. In the meantime, I'm going back to the old T10.. Design time data makes the other devs jealous.

**Comment by affans** [comment] 2016-04-28 23:12
So does anyone have a temporary solution to this? I just started learning UWP and its difficult to go through the code.

**Comment by callummoffat** [comment] 2016-04-28 23:30
Try turning off design-mode data, and see if it helps.

_Callum Moffat_
App Developer
Windows 10 Enthusiast

---

Keep track of the costs of your vehicles with Petrolhead!
https://www.microsoft.com/en-us/store/apps/petrolhead/9nblggh1rjqt?cid=phmailsig

**Comment by callummoffat** [comment] 2016-04-28 23:44
OK, I'm getting really annoyed. I realize this problem was not intentional, and that there are real benefits to using Behaviors 1.1.0. But I have to say, this strong-naming issue is really working my last nerve.

**Comment by jonwchu** [comment] 2016-04-29 00:33
It looks like wit #501ff9d

**Comment by jonwchu** [comment] 2016-04-29 00:36
It looks like with [a recent commit](https://github.com/Windows-XAML/Template10/commit/501ff9d1b6427d2c2d29b7c6c0445e9548d283c3) strong naming was turned on in T10, however strong naming was turned off with the latest release of Behaviors (v 1.1.0). Is it possible this might be causing some of the issues?

**Comment by callummoffat** [comment] 2016-04-29 00:58
That could be it, actually. Brilliant!

_Callum Moffat_
App Developer
Windows 10 Enthusiast

---

Keep track of the costs of your vehicles with Petrolhead!
https://www.microsoft.com/en-us/store/apps/petrolhead/9nblggh1rjqt?cid=phmailsig

**Comment by IIARROWS** [comment] 2016-04-29 06:15
@affans in the meantime, downgrade to template 10 1.1.8 and download behavior 1.0.3.

**Comment by sebfrie** [comment] 2016-04-29 23:35
In this case, could someone please revert [the mentioned commit](commit 501ff9d1b6427d2c2d29b7c6c0445e9548d283c3) asap (and upload a new nuget package)?

**Comment by callummoffat** [comment] 2016-05-03 04:26
Hey @JerryNixon,

Looks like a new thread has been opened on this topic (#904). Took longer than I thought it would, actually.
