### ISSUE TITLE
Null reference exception in XAML designer with third party components

### ISSUE THREAD

**Issue by schnitty** [Windows-XAML/Template10#1506] opened 2017-06-20 01:03 UTC
In certain situations if I have a relatively deep visual tree on a page
When I load the page for the first time and select the control the designer crashes with the following exception:
```
System.NullReferenceException
Object reference not set to an instance of an object.
at Microsoft.VisualStudio.DesignTools.Designer.Tools.Assets.ThemeContentProvider.SDKThemeContentDocumentRootResolver.ProvideResolvedUriForSDKContent(Uri relativeUri, String sourcePath)   
at Microsoft.VisualStudio.DesignTools.Designer.Tools.Assets.ThemeContentProvider.SDKThemeContentDocumentRootResolver.GetDocumentRoot(String path)   
at Microsoft.VisualStudio.DesignTools.Designer.Utility.ResourceSite.GetResolvedDocumentRootForSourceUri(IDocumentRootResolver documentRootResolver, DocumentCompositeNode resourceDictionaryNode, ICollection`1 warnings)   
at Microsoft.VisualStudio.DesignTools.Designer.Utility.ResourceSite.FindResourceInChildDictionary(IDocumentRootResolver documentRootResolver, XamlResourceKey key, ICollection`1 resourcesHostNodePath, ICollection`1 relatedRoots, ResourceDictionaryLink container, ICollection`1 warnings, DocumentCompositeNode resourceDictionaryReferenceNode)   
at Microsoft.VisualStudio.DesignTools.Designer.Utility.ResourceSite.FindResource(IDocumentRootResolver documentRootResolver, XamlResourceKey key, ICollection`1 resourcesHostNodePath, ICollection`1 relatedRoots, ResourceDictionaryLink container, Int32 numberOfChildrenToSearch, ICollection`1 warnings)   
at Microsoft.VisualStudio.DesignTools.Designer.Utility.ExpressionEvaluator.EvaluateResourceAtSpecificSite(ResourceSite resourceSite, XamlResourceKey key, ICollection`1 resourcesHostNodePath, ICollection`1 relatedRoots, Int32 lastResourceToSearch, ICollection`1 warnings, Boolean canReturnResourceTypeNode, Boolean evaluateRecursively, ICollection`1 seen)   
at Microsoft.VisualStudio.DesignTools.Designer.Utility.ExpressionEvaluator.EvaluateResourceAndCollectionPath(DocumentNodePath nodePath, ResourceReferenceType referenceType, XamlResourceKey key, ICollection`1 resourcesHostNodePath, ICollection`1 relatedRoots, ICollection`1 warnings, Boolean& invalidForwardReference, Boolean canReturnResourceTypeNode, Boolean evaluateRecursively)   
at Microsoft.VisualStudio.DesignTools.Designer.Utility.ExpressionEvaluator.EvaluateExpression(DocumentNodePath context, DocumentNode expression)   
at Microsoft.VisualStudio.DesignTools.Designer.Utility.ResourceHelper.FindReferencedResourcesInternal(DocumentNode root, IDocumentRootResolver documentRootResolver, Dictionary`2 visited, IList`1 resources)   
at Microsoft.VisualStudio.DesignTools.Designer.Utility.ResourceHelper.FindReferencedResources(DocumentNode root, IDocumentRootResolver documentRootResolver)   
at Microsoft.VisualStudio.DesignTools.Designer.Tools.Assets.ThemeContentProvider.FindResource(ResourceDictionaryContentProvider themeContent, IDocumentRootResolver documentRootResolver, String originalThemePath, String applicationThemeKey, Func`2 provideInstanceForThemeContent, Func`3 provideResolvedUriForMergedDictionary, Func`2 provideContentForMergedDictionary, XamlResourceKey key, IList`1& auxiliaryResources)   
at Microsoft.VisualStudio.DesignTools.Designer.Tools.Assets.ThemeContentProvider.FindResource(ResourceDictionaryContentProvider themeContent, IDocumentRootResolver documentRootResolver, String originalThemePath, String applicationThemeKey, Func`2 provideInstanceForThemeContent, Func`3 provideResolvedUriForMergedDictionary, Func`2 provideContentForMergedDictionary, XamlResourceKey key, IList`1& auxiliaryResources)   
at Microsoft.VisualStudio.DesignTools.Designer.Tools.Assets.ThemeContentProvider.GetResourceInternal(Dictionary`2 themeCache, IPlatform platform, IDocumentRootResolver documentRootResolver, String path, IAssembly themeAssembly, String relativeThemePath, IProjectContext projectContext, Func`3 provideResolvedUriForMergedDictionary, Func`2 provideContentForMergedDictionary, XamlResourceKey key, IList`1& auxiliaryResources)   
at Microsoft.VisualStudio.DesignTools.Designer.Tools.Assets.ThemeContentProvider.GetThemeResourceFromSdk(IProjectContext projectContext, IAssembly sdkAssembly, String sdkUniqueId, XamlResourceKey resourceKey, IList`1& auxiliaryResources)   
at Microsoft.VisualStudio.DesignTools.XamlDesigner.Commands.ReplaceStyleTemplateCommand.ResolveDefaultStyle(SceneNode targetElement, Object defaultStyleKey, Boolean allowDefaultStyle, DocumentNode& currentStyle, Boolean& isThemeStyle, IList`1& auxiliaryResources)   
at Microsoft.VisualStudio.DesignTools.XamlDesigner.Commands.ReplaceStyleTemplateCommand.ProvideCurrentStyle(SceneNode targetElement, IType targetType, PropertyReference targetPropertyReference, Boolean allowDefaultStyle, IList`1& auxiliaryResources)   
at Microsoft.VisualStudio.DesignTools.XamlDesigner.Commands.EditCopyOfStyleCommand.get_IsEnabled()   
at Microsoft.VisualStudio.DesignTools.Utility.Commands.Command.GetProperty(String propertyName, Object defaultValue)   
at Microsoft.VisualStudio.DesignTools.XamlDesigner.Commands.ReplaceStyleTemplateCommand.GetProperty(String propertyName)   
at Microsoft.VisualStudio.DesignTools.Designer.Views.SceneView.UpdateCommandState(IEnumerable`1 commandNames, Boolean forceRefresh)   
at Microsoft.VisualStudio.DesignTools.Designer.Views.SceneView.SelectionManager_LateActiveSceneUpdatePhase(Object sender, SceneUpdatePhaseEventArgs args)   
at Microsoft.VisualStudio.DesignTools.Designer.ViewModel.SceneUpdatePhaseEventHandler.Invoke(Object sender, SceneUpdatePhaseEventArgs e)   
at Microsoft.VisualStudio.DesignTools.Designer.ViewModel.Selection.SelectionManager.FireLateActiveSceneUpdatePhase(SceneUpdatePhaseEventArgs args)  
at Microsoft.VisualStudio.DesignTools.Designer.Views.SceneViewUpdateScheduleTask.UpdateLate()   
at Microsoft.VisualStudio.DesignTools.Utility.Scheduler.ScheduleTask.Update()  
at Microsoft.VisualStudio.DesignTools.Utility.Scheduler.SchedulingService.DispatchTasksAtPriority(DispatcherPriority priority)   
at Microsoft.VisualStudio.DesignTools.Utility.Scheduler.SchedulingService.DispatcherToken.Dispatch(Object arg)   
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)   
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)   
at System.Windows.Threading.DispatcherOperation.InvokeImpl()   
at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)  
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)   
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)   
at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)   
at System.Windows.Threading.DispatcherOperation.Invoke()   
at System.Windows.Threading.Dispatcher.ProcessQueue()   
at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)   
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)   
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)   
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)   
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)   
at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)   
at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)   
at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)   
at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)   
at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)   
at System.Windows.Application.RunDispatcher(Object ignore)   
at System.Windows.Application.RunInternal(Window window)   
at System.Windows.Application.Run(Window window)   
at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.DesignerProcess.RunApplication()  
at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.DesignerProcess.DesignProcessViewProvider.AppContainerDesignerProcessRun(String[] activationContextArgs)   
at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.DesignerProcess.DesignProcessViewProvider.<>c__DisplayClass3_0.<applicationView_Activated>b__0()   
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)   
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)   
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)   
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)   
at System.Threading.ThreadHelper.ThreadStart()
```

[ToolkitXamlDesignerBug.zip](https://github.com/Windows-XAML/Template10/files/1086620/ToolkitXamlDesignerBug.zip)

This is the simplest repro I have been able to create.  Not sure where the problem lies.  Could be with Template10, could be with Visual Studio 2017, could be with Third party control, could be a combination of all three.  I haven't been able to create a repro with just Template 10 stuff or with just third party control stuff.  It is only when I have Template 10 and a third party control where I see this issue.

I have just created a hamburger project and just added an ImageEx control within some nested group components (Grid, RelativePanel, etc)

I have attached a repro project that shows the issue.

Steps to reproduce:
Open solution and build in VS2017
Open solution in Blend 2017
Open MainPage.xaml
Directly select the ImageEx control in XAML
Exception is thrown.

I also have a video that shows the error using the same project if you require.

I'm not sure what is causing it.  Could it be because Template10 currently uses some old Windows SDK versions that other component makers aren't using and there is some kind of conflict or not able to find resources?  Not sure
  
Template 10 uses 10.0.14393.0 and the version published on [sdk archive]( https://developer.microsoft.com/en-us/windows/downloads/sdk-archive )is 10.0.14393.795

**Comment by schnitty** [comment] 2017-06-20 03:02
[XamlDesignerBugs.zip](https://github.com/Windows-XAML/Template10/files/1086883/XamlDesignerBugs.zip)

I accidentally uploaded the wrong repro before.  This is the correct one.  Sorry about that

**Comment by JerryNixon** [comment] 2017-07-28 16:31
Weird. This often occurs in controls that do something dangerous in the designer. If we can identify the property (sometimes it is the constructor) then we can wrap it in a Designer test and solve this. Several of our control have fallen victim to this over the years. Let me take a quick look.

**Comment by JerryNixon** [comment] 2017-07-28 16:39
Well, I am annoyed to report to you that after repeatedly clicking on and off the control in both Visual Studio and Blend, I can't get the error to occur in the designer. I create the project in VS as a non-T10 project, added ImageEx from Nuget and added it to MainPage. I loaded it up and clicked over and over waiting for the bomb. I do not have Telerik controls or anything else, just the ImageEx control. Because of this it is less likely the ImageEx control, but I am not closed to the idea that there might be a bug in it. There is so little code in this control, if you can figure out a hint of the problem, we can fix it, I am sure. I'm the meantime, I am going to close this issue because at its heart I cannot reproduce it.

**Closed as completed by JerryNixon** 2017-07-28 16:39 UTC
Labels: invalid
